In [9]:
from pathlib import Path
import pandas as pd

In [13]:
DATA_PATH = Path("../data/combined_dataset_labeled.xlsx")

df = pd.read_excel(
    DATA_PATH,
    sheet_name="Research Dataset"
)

df.shape

(1055, 84)

In [14]:
df["Tissue_Grade_Source"].value_counts(dropna=False)

Tissue_Grade_Source
Eye-bank form    1037
NaN                18
Name: count, dtype: int64

In [15]:
pd.crosstab(
    df["Dataset_Part"],
    df["Tissue_Grade_Source"],
    dropna=False
)

Tissue_Grade_Source          Eye-bank form  NaN
Dataset_Part
Graded set (eye-bank forms)           1037   18

In [16]:
df["Tissue_Grade"].value_counts(dropna=False)

Tissue_Grade
A+                                                                             543
A                                                                              311
B                                                                              167
NaN                                                                             19
A (release form; tissue sheet A+)                                                3
A (tissue sheet) / A+ (release form)                                             2
A (as read - verify)                                                             1
A+ / A (both circled on tissue sheet - verify)                                   1
B (release form A changed to B by hand; tissue sheet A)                          1
A+ (release; "-> B" handwritten)                                                 1
A+ (release form; handwritten mark may change to B - verify)                     1
A+ / A (both circled)                                                            1
A+ (as read)                                                                     1
B (release grade A changed to B by hand)                                         1
B (printed A+ on release form, handwritten downgrade to B; tissue sheet A+)      1
A (release form; tissue sheet circles A+)                                        1
Name: count, dtype: int64

In [17]:
pd.crosstab(
    df["Tissue_Grade_Source"],
    df["Tissue_Grade"],
    dropna=False
)

Tissue_Grade,A,A (as read - verify),A (release form; tissue sheet A+),A (release form; tissue sheet circles A+),A (tissue sheet) / A+ (release form),A+,A+ (as read),A+ (release form; handwritten mark may change to B - verify),"A+ (release; ""-> B"" handwritten)",A+ / A (both circled on tissue sheet - verify),A+ / A (both circled),B,"B (printed A+ on release form, handwritten downgrade to B; tissue sheet A+)",B (release form A changed to B by hand; tissue sheet A),B (release grade A changed to B by hand),NaN
Tissue_Grade_Source,,,,,,,,,,,,,,,,
Eye-bank form,311,1,3,1,2,543,1,1,1,1,1,167,1,1,1,1
NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18

In [18]:
df["Needs_Review"].value_counts(dropna=False)

Needs_Review
NaN    1055
Name: count, dtype: int64

In [19]:
df.loc[
    df["Needs_Review"].notna(),
    ["Tissue_ID", "Tissue_Grade", "Tissue_Grade_Source",
     "Needs_Review", "Review_Notes"]
].head(20)

Empty DataFrame
Columns: [Tissue_ID, Tissue_Grade, Tissue_Grade_Source, Needs_Review, Review_Notes]
Index: []

In [20]:
grade_counts = (
    df["Tissue_Grade"]
    .value_counts(dropna=False)
    .reset_index()
)

grade_counts.columns = ["Tissue_Grade", "Count"]

grade_counts

                                         Tissue_Grade  Count
0                                                  A+    543
1                                                   A    311
2                                                   B    167
3                                                 NaN     19
4                   A (release form; tissue sheet A+)      3
5                A (tissue sheet) / A+ (release form)      2
6                                A (as read - verify)      1
7      A+ / A (both circled on tissue sheet - verify)      1
8   B (release form A changed to B by hand; tissue...      1
9                    A+ (release; "-> B" handwritten)      1
10  A+ (release form; handwritten mark may change ...      1
11                              A+ / A (both circled)      1
12                                       A+ (as read)      1
13           B (release grade A changed to B by hand)      1
14  B (printed A+ on release form, handwritten dow...      1
15          A (release form; tissue sheet circles A+)      1

In [21]:
standard_grades = ["A+", "A", "B"]

non_standard = df[
    ~df["Tissue_Grade"].isin(standard_grades)
]

non_standard[
    ["Tissue_ID", "Tissue_Grade", "Tissue_Grade_Source"]
].sort_values("Tissue_Grade")

,Tissue_ID,Tissue_Grade,Tissue_Grade_Source
74,NEB-2020-10-12729 R,A (as read - verify),Eye-bank form
226,NEB-2024-05-16056 R,A (release form; tissue sheet A+),Eye-bank form
227,NEB-2024-05-16057 L,A (release form; tissue sheet A+),Eye-bank form
364,NEB-2024-08-16297 R,A (release form; tissue sheet A+),Eye-bank form
468,NEB-2025-09-17520 R,A (release form; tissue sheet circles A+),Eye-bank form
244,NEB-2024-05-16074 R,A (tissue sheet) / A+ (release form),Eye-bank form
319,NEB-2024-08-16252 L,A (tissue sheet) / A+ (release form),Eye-bank form
414,NEB-2025-09-17466 R,A+ (as read),Eye-bank form
321,NEB-2024-08-16254 L,A+ (release form; handwritten mark may change ...,Eye-bank form
302,NEB-2024-06-16133 L,"A+ (release; ""-> B"" handwritten)",Eye-bank form
230,NEB-2024-05-16060 R,A+ / A (both circled on tissue sheet - verify),Eye-bank form
371,NEB-2024-12-16603 R,A+ / A (both circled),Eye-bank form
443,NEB-2025-09-17495 R,"B (printed A+ on release form, handwritten dow...",Eye-bank form
231,NEB-2024-05-16061 L,B (release form A changed to B by hand; tissue...,Eye-bank form
430,NEB-2025-09-17482 R,B (release grade A changed to B by hand),Eye-bank form
0,12346 R (year/month unknown),NaN,NaN
42,NEB-2020-09-12695 L,NaN,NaN
44,NEB-2020-09-12697 L,NaN,NaN
45,NEB-2020-09-12698 L,NaN,NaN
46,NEB-2020-09-12699 R,NaN,NaN
47,NEB-2020-09-12700 L,NaN,NaN
48,NEB-2020-09-12701 R,NaN,NaN
97,NEB-2020-10-12761 R,NaN,NaN
98,NEB-2020-10-12763 L,NaN,NaN
99,NEB-2020-10-12772 L,NaN,NaN
164,NEB-2022-04-13848 R,NaN,NaN
174,14302 L (year/month unknown),NaN,NaN
285,NEB-2024-06-16116 L,NaN,NaN
286,NEB-2024-06-16117 R,NaN,NaN
306,NEB-2024-06-16137 L,NaN,NaN
373,NEB-2024-12-16605 L,NaN,NaN
405,NEB-2025-09-17457 L,NaN,NaN
531,NEB-2025-10-17585 R,NaN,NaN
591,NEB-2023-01-14657 R,NaN,Eye-bank form

In [22]:
non_standard[
    ["Tissue_ID", "Tissue_Grade", "Tissue_Grade_Source"]
].to_string(index=False)

'                   Tissue_ID                                                                Tissue_Grade Tissue_Grade_Source\n12346 R (year/month unknown)                                                                         NaN                 NaN\n         NEB-2020-09-12695 L                                                                         NaN                 NaN\n         NEB-2020-09-12697 L                                                                         NaN                 NaN\n         NEB-2020-09-12698 L                                                                         NaN                 NaN\n         NEB-2020-09-12699 R                                                                         NaN                 NaN\n         NEB-2020-09-12700 L                                                                         NaN                 NaN\n         NEB-2020-09-12701 R                                                                         NaN                 NaN\n         NEB-2020-10-12729 R                                                        A (as read - verify)       Eye-bank form\n         NEB-2020-10-12761 R                                                                         NaN                 NaN\n         NEB-2020-10-12763 L                                                                         NaN                 NaN\n         NEB-2020-10-12772 L                                                                         NaN                 NaN\n         NEB-2022-04-13848 R                                                                         NaN                 NaN\n14302 L (year/month unknown)                                                                         NaN                 NaN\n         NEB-2024-05-16056 R                                           A (release form; tissue sheet A+)       Eye-bank form\n         NEB-2024-05-16057 L                                           A (release form; tissue sheet A+)       Eye-bank form\n         NEB-2024-05-16060 R                              A+ / A (both circled on tissue sheet - verify)       Eye-bank form\n         NEB-2024-05-16061 L                     B (release form A changed to B by hand; tissue sheet A)       Eye-bank form\n         NEB-2024-05-16074 R                                        A (tissue sheet) / A+ (release form)       Eye-bank form\n         NEB-2024-06-16116 L                                                                         NaN                 NaN\n         NEB-2024-06-16117 R                                                                         NaN                 NaN\n         NEB-2024-06-16133 L                                            A+ (release; "-> B" handwritten)       Eye-bank form\n         NEB-2024-06-16137 L                                                                         NaN                 NaN\n         NEB-2024-08-16252 L                                        A (tissue sheet) / A+ (release form)       Eye-bank form\n         NEB-2024-08-16254 L                A+ (release form; handwritten mark may change to B - verify)       Eye-bank form\n         NEB-2024-08-16297 R                                           A (release form; tissue sheet A+)       Eye-bank form\n         NEB-2024-12-16603 R                                                       A+ / A (both circled)       Eye-bank form\n         NEB-2024-12-16605 L                                                                         NaN                 NaN\n         NEB-2025-09-17457 L                                                                         NaN                 NaN\n         NEB-2025-09-17466 R                                                                A+ (as read)       Eye-bank form\n         NEB-2025-09-17482 R                                    B (release grade A changed to B by hand)       Eye-bank form\n         NEB-2025-09-17495 R B (printed A+ on release form, handwritten downgrade to B; tissue sheet A+)       Eye-bank form\n         NEB-2025-09-17520 R                                   A (release form; tissue sheet circles A+)       Eye-bank form\n         NEB-2025-10-17585 R                                                                         NaN                 NaN\n         NEB-2023-01-14657 R                                                                         NaN       Eye-bank form'

In [23]:
review_grades = {
    "12729": "A",
    "16056": "A",
    "16057": "A",
    "16060": "A",
    "16061": "B",
    "16074": "A+",
    "16133": "B",
    "16252": "A+",
    "16254": "B",
    "16297": "A",
    "16603": "A",
    "17466": "A",
    "17482": "B",
    "17495": "B",
    "17520": "A",
}

# Keep the original grade untouched
df["Tissue_Grade_Clean"] = df["Tissue_Grade"]

# Extract the numeric tissue ID from Tissue_ID
tissue_number = (
    df["Tissue_ID"]
    .astype(str)
    .str.extract(r"(\d{5})")[0]
)

# Apply specialist-reviewed grades
mask = tissue_number.isin(review_grades)

df.loc[mask, "Tissue_Grade_Clean"] = tissue_number[mask].map(review_grades)

In [24]:
df.loc[
    mask,
    ["Tissue_ID", "Tissue_Grade", "Tissue_Grade_Clean"]
].sort_values("Tissue_ID")

,Tissue_ID,Tissue_Grade,Tissue_Grade_Clean
74,NEB-2020-10-12729 R,A (as read - verify),A
226,NEB-2024-05-16056 R,A (release form; tissue sheet A+),A
227,NEB-2024-05-16057 L,A (release form; tissue sheet A+),A
230,NEB-2024-05-16060 R,A+ / A (both circled on tissue sheet - verify),A
231,NEB-2024-05-16061 L,B (release form A changed to B by hand; tissue...,B
244,NEB-2024-05-16074 R,A (tissue sheet) / A+ (release form),A+
302,NEB-2024-06-16133 L,"A+ (release; ""-> B"" handwritten)",B
319,NEB-2024-08-16252 L,A (tissue sheet) / A+ (release form),A+
321,NEB-2024-08-16254 L,A+ (release form; handwritten mark may change ...,B
364,NEB-2024-08-16297 R,A (release form; tissue sheet A+),A
371,NEB-2024-12-16603 R,A+ / A (both circled),A
414,NEB-2025-09-17466 R,A+ (as read),A
430,NEB-2025-09-17482 R,B (release grade A changed to B by hand),B
443,NEB-2025-09-17495 R,"B (printed A+ on release form, handwritten dow...",B
468,NEB-2025-09-17520 R,A (release form; tissue sheet circles A+),A

In [25]:
df["Tissue_Grade_Clean"].value_counts(dropna=False)

Tissue_Grade_Clean
A+     545
A      319
B      172
NaN     19
Name: count, dtype: int64

In [26]:
missing_grades = df[
    df["Tissue_Grade_Clean"].isna()
]

missing_grades[
    ["Tissue_ID", "Tissue_Grade", "Tissue_Grade_Source"]
].to_string(index=False)

'                   Tissue_ID Tissue_Grade Tissue_Grade_Source\n12346 R (year/month unknown)          NaN                 NaN\n         NEB-2020-09-12695 L          NaN                 NaN\n         NEB-2020-09-12697 L          NaN                 NaN\n         NEB-2020-09-12698 L          NaN                 NaN\n         NEB-2020-09-12699 R          NaN                 NaN\n         NEB-2020-09-12700 L          NaN                 NaN\n         NEB-2020-09-12701 R          NaN                 NaN\n         NEB-2020-10-12761 R          NaN                 NaN\n         NEB-2020-10-12763 L          NaN                 NaN\n         NEB-2020-10-12772 L          NaN                 NaN\n         NEB-2022-04-13848 R          NaN                 NaN\n14302 L (year/month unknown)          NaN                 NaN\n         NEB-2024-06-16116 L          NaN                 NaN\n         NEB-2024-06-16117 R          NaN                 NaN\n         NEB-2024-06-16137 L          NaN                 NaN\n         NEB-2024-12-16605 L          NaN                 NaN\n         NEB-2025-09-17457 L          NaN                 NaN\n         NEB-2025-10-17585 R          NaN                 NaN\n         NEB-2023-01-14657 R          NaN       Eye-bank form'

In [29]:
# Final grading summary
grade_summary = (
    df["Tissue_Grade_Clean"]
    .value_counts(dropna=False)
    .rename_axis("Tissue_Grade_Clean")
    .reset_index(name="Count")
)

print(grade_summary)

  Tissue_Grade_Clean  Count
0                 A+    545
1                  A    319
2                  B    172
3                NaN     19

In [33]:
print(df["ECD_CD_cells_per_mm2"].describe())

count     956.000000
mean     2581.553347
std       468.981048
min         0.000000
25%      2336.000000
50%      2591.000000
75%      2857.000000
max      4484.000000
Name: ECD_CD_cells_per_mm2, dtype: float64

In [34]:
print((df["ECD_CD_cells_per_mm2"] == 0).sum())

4

In [35]:
print(df.loc[
    df["ECD_CD_cells_per_mm2"] == 0,
    [
        "Tissue_ID",
        "Tissue_Grade_Clean",
        "ECD_CD_cells_per_mm2",
        "CV",
        "HEX_percent",
        "SD",
        "Total_Cell_Count"
    ]
])

               Tissue_ID Tissue_Grade_Clean  ECD_CD_cells_per_mm2   CV  \
677  NEB-2023-03-14825 R                  B                   0.0  0.0
818  NEB-2023-05-15117 R                  B                   0.0  0.0
833  NEB-2023-06-15153 R                  B                   0.0  0.0
890  NEB-2023-07-15267 R                  B                   0.0  0.0

     HEX_percent   SD  Total_Cell_Count
677          0.0  0.0               0.0
818          0.0  0.0               0.0
833          0.0  0.0               0.0
890          0.0  0.0               0.0

In [38]:
konan_measurement_cols = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2"
]

invalid_konan = df["ECD_CD_cells_per_mm2"] == 0

df.loc[invalid_konan, konan_measurement_cols] = pd.NA

print(invalid_konan.sum())

0

In [39]:
df.loc[
    invalid_konan,
    ["Tissue_ID", "Tissue_Grade_Clean"] + konan_measurement_cols
]

Empty DataFrame
Columns: [Tissue_ID, Tissue_Grade_Clean, ECD_CD_cells_per_mm2, CV, HEX_percent, SD, Total_Cell_Count, Total_Area_um2]
Index: []

In [40]:
df.loc[
    df["Tissue_ID"].isin([
        "NEB-2023-03-14825 R",
        "NEB-2023-05-15117 R",
        "NEB-2023-06-15153 R",
        "NEB-2023-07-15267 R"
    ]),
    ["Tissue_ID", "Tissue_Grade_Clean"] + konan_measurement_cols
]

,Tissue_ID,Tissue_Grade_Clean,ECD_CD_cells_per_mm2,CV,HEX_percent,SD,Total_Cell_Count,Total_Area_um2
677,NEB-2023-03-14825 R,B,NaN,NaN,NaN,NaN,NaN,NaN
818,NEB-2023-05-15117 R,B,NaN,NaN,NaN,NaN,NaN,NaN
833,NEB-2023-06-15153 R,B,NaN,NaN,NaN,NaN,NaN,NaN
890,NEB-2023-07-15267 R,B,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
print((df[konan_measurement_cols] == 0).sum())

ECD_CD_cells_per_mm2    0
CV                      0
HEX_percent             0
SD                      0
Total_Cell_Count        0
Total_Area_um2          0
dtype: int64

In [45]:
leakage_candidates = [
    "Overall_Donor_Quality",
    "Transplant_Suitability",
    "Suitability_Reason",
    "Tissue_Outcome",
    "Recipient_Age",
    "Recipient_Eye",
    "Recipient_Indication",
    "Request_Indication",
    "Primary_Procedure",
    "Secondary_Procedures",
    "Surgery_Date",
    "Requested_Grade",
    "Planned_Procedure",
    "Grade_Request_Met",
    "Review_Notes",
    "Additional_Findings"
]

for col in leakage_candidates:
    print(f"\n--- {col} ---")
    print(df[col].dropna().value_counts().head(10))

--- Overall_Donor_Quality ---
Overall_Donor_Quality
Excellent                                                          137
Very good                                                           79
Good                                                                31
Very good (as read)                                                  4
Excellent (as read)                                                  2
Good (as read)                                                       2
Good (Very good struck)                                              2
Excellent / very good (mark spans both - verify)                     2
Very good (Good also marked - verify)                                1
Very good (stroke runs across Excellent and Very good - verify)      1
Name: count, dtype: int64

--- Transplant_Suitability ---
Transplant_Suitability
Suitable (released for surgery - printed release form)                                                       197
Suitable                                                                                                     177
Not stated (no release form in PDF); donor sheet grade A+                                                      9
Not ticked on Donor Form B                                                                                     9
Released (printed release form); Donor Form B suitability unticked                                             7
Suitable (Donor Form B; released for surgery - printed release form)                                           7
Suitable (released for surgery - printed release form); Donor Form B stroke crosses suitable/not suitable      5
Not stated (no release form in PDF); donor sheet grade A                                                       4
Suitable (released for surgery - printed release form; Donor Form B unticked)                                  3
Donor suitable for transplant, overall quality excellent (donor form back page); no release form               3
Name: count, dtype: int64

--- Suitability_Reason ---
Suitability_Reason
Not stated on Donor Form B          2
Hepatitis C positive - discarded    2
Name: count, dtype: int64

--- Tissue_Outcome ---
Tissue_Outcome
Exported - cornea sent to Dr Y.Y. Choong, Malaysia, 23/09/2025 (handwritten note)        3
Allocated to Dr Pattaramon, Rutnin Medical, Thailand (29/09/2020)                        2
No transplant recorded (report form blank)                                               2
Cornea expired on 03.01.2025 (handwritten)                                               2
Exported - cornea sent to KPJ Eye Specialist, Malaysia, 26/12/2024 (handwritten note)    2
Cornea expired 16/10/2025 (handwritten note)                                             2
Cornea expired on 23.10.2025 (handwritten)                                               2
Cornea expired on 28.10.2025 (handwritten)                                               2
Cornea expired on 31/10/2025 (handwritten)                                               2
Cornea expired 11/11/2025 (handwritten note)                                             2
Name: count, dtype: int64

--- Recipient_Age ---
Recipient_Age
69    8
60    8
67    8
48    7
64    7
70    7
74    7
44    7
80    6
21    6
Name: count, dtype: int64

--- Recipient_Eye ---
Recipient_Eye
Left                                                          122
Right                                                         111
Left (request form)                                             7
Conflict: Right (request form) vs Left (transplant report)      4
Right (request form)                                            3
Left (request; eye unticked on transplant report)               3
Conflict: Left (request form) vs Right (transplant report)      2
Right (request; not ticked on report)                           2
Right (transplant report; request ticks Left)                   2
Left (transplant report; request ticks Right - verify)          2
Name: count, dtype: int64

--- Recipient_Indication ---
Recipient_Indication
Advanced keratoconus                           15
Failed graft                                   12
Keratoconus                                    11
Decompensated cornea                            9
Corneal scar                                    8
Advanced keratoconus (VA 6/60; fellow 6/60)     8
Rejected graft                                  4
Right decompensated cornea                      3
Right corneal ulcer                             3
Corneal ulcer (VA HM; fellow 6/6)               2
Name: count, dtype: int64

--- Request_Indication ---
Request_Indication
Optical (routine); Grade A+ requested; planned PK          40
Optical (routine); Grade B requested; planned DALK         28
Optical (routine); Grade A+ requested; planned DSEK        18
Therapeutic (routine); Grade A requested; planned PK        8
Optical                                                     6
Optical (routine)                                           6
Therapeutic (emergency)                                     5
Optical (routine); Grade A+ requested; planned PK + IOL     5
Therapeutic (routine); Grade A+ requested; planned DSEK     4
Therapeutic (emergency); Grade A+ requested; planned PK     4
Name: count, dtype: int64

--- Primary_Procedure ---
Primary_Procedure
Penetrating keratoplasty                             150
Lamellar keratoplasty                                 12
Lamellar keratoplasty (DALK)                           8
PK (planned, request form)                             6
Lamellar keratoplasty (DALK planned)                   6
Lamellar keratoplasty (DSEK planned)                   5
Penetrating keratoplasty (repeat)                      5
Lamellar keratoplasty (DALK per request)               4
Lamellar keratoplasty (DALK planned; no LK page)       4
Lamellar keratoplasty (DSEK - "Others" on report)      4
Name: count, dtype: int64

--- Secondary_Procedures ---
Secondary_Procedures
Not ticked                                                24
No secondary procedures                                   17
None ticked                                                9
PC/IOL                                                     9
Peripheral iridectomy                                      2
Not recorded (none ticked)                                 2
Not recorded                                               2
ICCE; anterior vitrectomy; peripheral iridectomy           1
None ticked (LK page note: 'Anterior vitrectomy done')     1
ECCE                                                       1
Name: count, dtype: int64

--- Surgery_Date ---
Surgery_Date
2024-06-26    7
2024-08-21    6
2020-09-28    5
2024-05-22    5
2024-06-12    5
2024-12-24    5
2025-10-01    5
2020-09-26    4
2020-09-30    4
2020-09-23    4
Name: count, dtype: int64

--- Requested_Grade ---
Requested_Grade
A+                                105
B                                  41
A                                  28
A+ / A (both ticked)               13
A / B (both ticked)                 3
A+, A                               3
A+ (back-up) / B (both ticked)      1
A+ / B (both ticked)                1
A, B                                1
Name: count, dtype: int64

--- Planned_Procedure ---
Planned_Procedure
PK                         109
DALK                        36
DSEK                        27
PK + IOL                     5
PK / DSEK (both ticked)      3
DALK / PK                    2
Other: patch graft           2
Other: PKP under GA          2
PKP                          2
DALK (DSEK also marked)      1
Name: count, dtype: int64

--- Grade_Request_Met ---
Grade_Request_Met
Yes              120
Exceeded          43
Below request     33
Name: count, dtype: int64

--- Review_Notes ---
Review_Notes
Folds call uncertain                                                                                                                            43
Guttata call uncertain                                                                                                                          16
CD 2538 within 50 of the 2,500 A/A+ cut-off                                                                                                     10
Guttata call uncertain; Guttata label (reference: ~50% A at CD ≥ 2,500)                                                                          7
Guttata label (reference: ~50% A at CD ≥ 2,500)                                                                                                  7
CD in 2200–2300 borderline zone; CD 2268 within 50 of the 2,250 B/A cut-off                                                                      6
CD 2506 within 50 of the 2,500 A/A+ cut-off                                                                                                      6
CD 2532 within 50 of the 2,500 A/A+ cut-off                                                                                                      5
Report shows CD/CV/HEX/SD = 0 (no cell count obtained); image-based checks skipped; CD = 0 (poor cornea) → B; only 1 reference case, confirm     4
Folds call uncertain; Guttata call uncertain                                                                                                     4
Name: count, dtype: int64

--- Additional_Findings ---
Additional_Findings
Rim 3-4; cornea diameter 11 mm; corneoscleral 18 mm        61
Rim 3-3.5; cornea diameter 11 mm; corneoscleral 18 mm      17
Rim 2.5-3.5; cornea diameter 11 mm; corneoscleral 18 mm    13
Rim 2.5-4; cornea diameter 11 mm; corneoscleral 18 mm      10
Rim 3-5; cornea diameter 11 mm; corneoscleral 18 mm        10
Rim 2-3; cornea diameter 11 mm; corneoscleral 18 mm         9
Rim 2.5-3; cornea diameter 11 mm; corneoscleral 18 mm       6
Rim 3 mm; cornea diameter 11 mm; corneoscleral 18 mm        6
Rim 3-4.5; cornea diameter 11 mm; corneoscleral 18 mm       5
Rim 2.5-3; cornea diameter 11 mm; corneoscleral 17 mm       5
Name: count, dtype: int64

In [46]:
leakage_columns = [
    "Overall_Donor_Quality",
    "Transplant_Suitability",
    "Suitability_Reason",
    "Tissue_Outcome",
    "Recipient_Age",
    "Recipient_Eye",
    "Recipient_Indication",
    "Request_Indication",
    "Primary_Procedure",
    "Secondary_Procedures",
    "Surgery_Date",
    "Requested_Grade",
    "Planned_Procedure",
    "Grade_Request_Met",
    "Review_Notes"
]

len(leakage_columns)

15

In [48]:
grade_mentions = df["Additional_Findings"].dropna()[
    df["Additional_Findings"].dropna().str.contains(
        r"\bGrade\s*(A\+|A|B)\b",
        case=False,
        regex=True,
        na=False
    )
]

print(grade_mentions)

156    Release form: Grade A+, irregular cut; rim 2.5...
157    Release form: Grade A+, irregular cut; rim 2.5...
165    Release form: Grade A+, irregular cut, pterygi...
173    Release form: Grade A, irregular cut, mild ict...
175    Release form: Grade A, irregular cut, mild ict...
                             ...
574    Release form: Grade A+, irregular cut; rim 3.0...
576    Release form: Grade B, irregular cut; rim 3.00...
584    Release form: Grade A, irregular cut; rim 2.00...
585    Release form: Grade A+, irregular cut; rim 3.0...
589    Release form: Grade A+, irregular cut, eye las...
Name: Additional_Findings, Length: 255, dtype: str

C:\Users\pulit\AppData\Local\Temp\ipykernel_2836\1925329226.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Additional_Findings"].dropna().str.contains(

In [49]:
leakage_columns = [
    "Overall_Donor_Quality",
    "Transplant_Suitability",
    "Suitability_Reason",
    "Tissue_Outcome",
    "Recipient_Age",
    "Recipient_Eye",
    "Recipient_Indication",
    "Request_Indication",
    "Primary_Procedure",
    "Secondary_Procedures",
    "Surgery_Date",
    "Requested_Grade",
    "Planned_Procedure",
    "Grade_Request_Met",
    "Review_Notes",
    "Additional_Findings"
]

In [50]:
len(leakage_columns)

16

In [51]:
numeric_cols = df.select_dtypes(include="number").columns

In [54]:
print(df[numeric_cols].corr().round(2))

                          ECD_CD_cells_per_mm2    CV  HEX_percent    SD  \
ECD_CD_cells_per_mm2                      1.00 -0.04         0.02 -0.75
CV                                       -0.04  1.00        -0.51  0.53
HEX_percent                               0.02 -0.51         1.00 -0.28
SD                                       -0.75  0.53        -0.28  1.00
Total_Cell_Count                          0.26 -0.04         0.15 -0.33
Total_Area_um2                           -0.64  0.03         0.09  0.42
Donor_Age                                -0.20  0.12        -0.03  0.17
Tissue_Serial                            -0.06  0.02        -0.02 -0.00
PDF_Pages                                 0.04 -0.02        -0.04 -0.08
Konan_Mean_Cell_Area_um2                 -0.89  0.10        -0.06  0.88
Death_to_Surgery_Days                    -0.21  0.10        -0.09  0.24
Request_to_Surgery_Days                   0.07 -0.17         0.11 -0.17
Needs_Review                               NaN   NaN          NaN   NaN

                          Total_Cell_Count  Total_Area_um2  Donor_Age  \
ECD_CD_cells_per_mm2                  0.26           -0.64      -0.20
CV                                   -0.04            0.03       0.12
HEX_percent                           0.15            0.09      -0.03
SD                                   -0.33            0.42       0.17
Total_Cell_Count                      1.00            0.53      -0.10
Total_Area_um2                        0.53            1.00       0.10
Donor_Age                            -0.10            0.10       1.00
Tissue_Serial                         0.10            0.10      -0.04
PDF_Pages                             0.03           -0.03      -0.04
Konan_Mean_Cell_Area_um2             -0.36            0.52       0.16
Death_to_Surgery_Days                 0.05            0.20      -0.00
Request_to_Surgery_Days               0.00           -0.07       0.07
Needs_Review                           NaN             NaN        NaN

                          Tissue_Serial  PDF_Pages  Konan_Mean_Cell_Area_um2  \
ECD_CD_cells_per_mm2              -0.06       0.04                     -0.89
CV                                 0.02      -0.02                      0.10
HEX_percent                       -0.02      -0.04                     -0.06
SD                                -0.00      -0.08                      0.88
Total_Cell_Count                   0.10       0.03                     -0.36
Total_Area_um2                     0.10      -0.03                      0.52
Donor_Age                         -0.04      -0.04                      0.16
Tissue_Serial                      1.00       0.21                      0.01
PDF_Pages                          0.21       1.00                     -0.08
Konan_Mean_Cell_Area_um2           0.01      -0.08                      1.00
Death_to_Surgery_Days              0.14       0.04                      0.20
Request_to_Surgery_Days            0.04       0.05                     -0.07
Needs_Review                        NaN        NaN                       NaN

                          Death_to_Surgery_Days  Request_to_Surgery_Days  \
ECD_CD_cells_per_mm2                      -0.21                     0.07
CV                                         0.10                    -0.17
HEX_percent                               -0.09                     0.11
SD                                         0.24                    -0.17
Total_Cell_Count                           0.05                     0.00
Total_Area_um2                             0.20                    -0.07
Donor_Age                                 -0.00                     0.07
Tissue_Serial                              0.14                     0.04
PDF_Pages                                  0.04                     0.05
Konan_Mean_Cell_Area_um2                   0.20                    -0.07
Death_to_Surgery_Days                      1.00                    -0.18
Request_to_Surgery_Days                   -0.18                     1.00
Needs_Review                                NaN                      NaN

                          Needs_Review
ECD_CD_cells_per_mm2               NaN
CV                                 NaN
HEX_percent                        NaN
SD                                 NaN
Total_Cell_Count                   NaN
Total_Area_um2                     NaN
Donor_Age                          NaN
Tissue_Serial                      NaN
PDF_Pages                          NaN
Konan_Mean_Cell_Area_um2           NaN
Death_to_Surgery_Days              NaN
Request_to_Surgery_Days            NaN
Needs_Review                       NaN

In [55]:
# Inspect numerical columns

print(df[numeric_cols].describe())

       ECD_CD_cells_per_mm2          CV  HEX_percent          SD  \
count            952.000000  952.000000   952.000000  951.000000
mean            2592.400210   38.130252    54.032563  153.001052
std              438.998119    4.993776     6.437436   47.701319
min              676.000000   24.000000    27.000000   86.000000
25%             2336.000000   35.000000    50.000000  127.000000
50%             2591.000000   38.000000    54.000000  144.000000
75%             2857.000000   41.000000    58.000000  164.000000
max             4484.000000   74.000000    76.000000  753.000000

       Total_Cell_Count  Total_Area_um2    Donor_Age  Tissue_Serial  \
count        952.000000      952.000000  1050.000000    1055.000000
mean         107.018908    42265.138655    59.672381   15353.921327
std           16.351349     9122.697304    10.901732    1462.541930
min           10.000000     5071.000000    15.000000   12346.000000
25%          104.000000    37512.500000    54.000000   14739.500000
50%          108.000000    41464.500000    62.000000   15285.000000
75%          113.000000    46336.500000    68.000000   16259.500000
max          204.000000   100692.000000    78.000000   17650.000000

        PDF_Pages  Konan_Mean_Cell_Area_um2  Death_to_Surgery_Days  \
count  591.000000                956.000000             237.000000
mean     4.231810                398.596234               4.995781
std      1.937691                 99.833433               2.946555
min      1.000000                  0.000000               0.000000
25%      3.000000                350.000000               3.000000
50%      4.000000                386.000000               4.000000
75%      5.000000                427.250000               7.000000
max     17.000000               1479.000000              15.000000

       Request_to_Surgery_Days  Needs_Review
count               164.000000           0.0
mean                  2.841463           NaN
std                  10.096430           NaN
min                 -16.000000           NaN
25%                   1.000000           NaN
50%                   1.000000           NaN
75%                   3.000000           NaN
max                 123.000000           NaN

In [56]:
df["Needs_Review"].isna().all()

np.True_

In [58]:
unusable_columns = [
    "Needs_Review"
]

In [59]:
text_numeric_candidates = [
    "Form_ECD_cells_per_mm2",
    "Recipient_Age",
    "Donor_Graft_Size_mm",
    "Recipient_Bed_Size_mm",
    "Previous_Grafts"
]

for col in text_numeric_candidates:
    print(f"\n--- {col} ---")
    print(df[col].dropna().head(15).to_list())

--- Form_ECD_cells_per_mm2 ---
[2132, 2212, 2538, 2584, 3115, 2950, 2993, 3049, 2833, 2780, 3049, 2710, 2625, 2833, 3012]

--- Recipient_Age ---
[48, 64, 53, 57, '2 y 3 m', '35', 80, '60 (as read)', 68, 47, 14, 69, '72 (as read)', 55, 21]

--- Donor_Graft_Size_mm ---
[8.25, 8, 8.5, 7.5, 8.5, 9, 7, 11, 7.5, 8, 8, '8-8.5', '8 (as read)', 8.25, 8]

--- Recipient_Bed_Size_mm ---
[8, 8.5, 8, 8, 8.25, 7.5, 7, 8.5, 8.25, '8 (as read)', '8 (as read)', 7.5, 9, '11.5 (as read)', 8.5]

--- Previous_Grafts ---
['1', '2', '1', 'Not ticked (diagnosis implies >=1)', '1', '1', 'Not ticked', '1', 'Not ticked', '>=1 (repeat PK)', 0, 1, 0, 1, 2]

In [60]:
df["Form_ECD_cells_per_mm2"] = pd.to_numeric(
    df["Form_ECD_cells_per_mm2"],
    errors="coerce"
)

df["Form_ECD_cells_per_mm2"].dtype

dtype('float64')

In [62]:
print(df["Form_ECD_cells_per_mm2"].describe())

count     575.000000
mean     2659.478261
std       464.859121
min       676.000000
25%      2392.000000
50%      2639.000000
75%      2937.000000
max      4484.000000
Name: Form_ECD_cells_per_mm2, dtype: float64

In [64]:
age_text_values = df.loc[
    df["Recipient_Age"].notna() &
    ~df["Recipient_Age"].astype(str).str.fullmatch(r"\d+(\.\d+)?"),
    "Recipient_Age"
]

print(age_text_values.value_counts())

Recipient_Age
60 (as read)                                           2
17 (as read)                                           2
21 (as read)                                           2
2 y 3 m                                                1
72 (as read)                                           1
18 (as read)                                           1
13 (as read)                                           1
67 (as read)                                           1
6/12 (as read - possibly 6 months)                     1
30 (as read)                                           1
9.5 (written "9 1/2 yr")                               1
68 (report) / 72 (request)                             1
71 (as read)                                           1
3 y 5 m (written "3 5/12")                             1
64 (request; transplant report 60 as read)             1
31 (as read)                                           1
53 (request; transplant report 52)                     1
76 (request; transplant report 74)                     1
57 (request; transplant report 52 as read)             1
69 (report) / 65 (request, as read)                    1
78 (report) / 70 (request)                             1
44 (request); 43 (transplant report)                   1
46 (transplant report); request reads 40 (verify)      1
64 (request); 54 (transplant report)                   1
81 (as read)                                           1
84 (as read)                                           1
33 (request; transplant report 32)                     1
39 (request; transplant report 35)                     1
61 (as read)                                           1
36 (as read)                                           1
40 (as read)                                           1
54 (as read)                                           1
8 (as read - verify)                                   1
38 (as read)                                           1
68 (transplant report; request as read 64 - verify)    1
66 (transplant report; request 60 - verify)            1
65 (as read)                                           1
Name: count, dtype: int64

In [66]:
age_conflicts = df.loc[
    df["Recipient_Age"].notna() &
    df["Recipient_Age"].astype(str).str.contains(
        r"/|request.*report|report.*request",
        case=False,
        regex=True,
        na=False
    ),
    ["Tissue_ID", "Recipient_Age"]
]

print(age_conflicts)

               Tissue_ID                                      Recipient_Age
44   NEB-2020-09-12697 L                 6/12 (as read - possibly 6 months)
79   NEB-2020-10-12734 L                           9.5 (written "9 1/2 yr")
84   NEB-2020-10-12739 L                         68 (report) / 72 (request)
242  NEB-2024-05-16072 L                         3 y 5 m (written "3 5/12")
275  NEB-2024-05-16105 R         64 (request; transplant report 60 as read)
287  NEB-2024-06-16118 L                 53 (request; transplant report 52)
291  NEB-2024-06-16122 R                 76 (request; transplant report 74)
297  NEB-2024-06-16128 L         57 (request; transplant report 52 as read)
322  NEB-2024-08-16255 R                69 (report) / 65 (request, as read)
329  NEB-2024-08-16262 L                         78 (report) / 70 (request)
347  NEB-2024-08-16280 R               44 (request); 43 (transplant report)
355  NEB-2024-08-16288 R  46 (transplant report); request reads 40 (verify)
361  NEB-2024-08-16294 L               64 (request); 54 (transplant report)
478  NEB-2025-09-17530 R                 33 (request; transplant report 32)
481  NEB-2025-10-17533 R                 39 (request; transplant report 35)
567  NEB-2025-11-17625 L  68 (transplant report; request as read 64 - ve...
570  NEB-2025-11-17628 R        66 (transplant report; request 60 - verify)

In [67]:
df["Recipient_Age_Clean"] = df["Recipient_Age"]

In [68]:
verified_recipient_ages = {
    "NEB-2020-09-12697 L": 21,
    "NEB-2020-10-12739 L": 58,
    "NEB-2024-05-16072 L": 35,
    "NEB-2024-05-16105 R": 52,
    "NEB-2024-06-16118 L": 58,
    "NEB-2024-06-16122 R": 38,
    "NEB-2024-06-16128 L": 19,
    "NEB-2024-08-16255 R": 64,
    "NEB-2024-08-16262 L": 56,
    "NEB-2024-08-16280 R": 41,
    "NEB-2024-08-16288 R": 60,
    "NEB-2024-08-16294 L": 55,
    "NEB-2025-09-17530 R": 62,
    "NEB-2025-10-17533 R": 45,
    "NEB-2025-11-17625 L": 60,
    "NEB-2025-11-17628 R": 62,
}

In [69]:
df.loc[
    df["Tissue_ID"].isin(verified_recipient_ages),
    "Recipient_Age_Clean"
] = df.loc[
    df["Tissue_ID"].isin(verified_recipient_ages),
    "Tissue_ID"
].map(verified_recipient_ages)

In [71]:
print(df.loc[
    df["Tissue_ID"].isin(verified_recipient_ages),
    ["Tissue_ID", "Recipient_Age", "Recipient_Age_Clean"]
])

               Tissue_ID                                      Recipient_Age  \
44   NEB-2020-09-12697 L                 6/12 (as read - possibly 6 months)
84   NEB-2020-10-12739 L                         68 (report) / 72 (request)
242  NEB-2024-05-16072 L                         3 y 5 m (written "3 5/12")
275  NEB-2024-05-16105 R         64 (request; transplant report 60 as read)
287  NEB-2024-06-16118 L                 53 (request; transplant report 52)
291  NEB-2024-06-16122 R                 76 (request; transplant report 74)
297  NEB-2024-06-16128 L         57 (request; transplant report 52 as read)
322  NEB-2024-08-16255 R                69 (report) / 65 (request, as read)
329  NEB-2024-08-16262 L                         78 (report) / 70 (request)
347  NEB-2024-08-16280 R               44 (request); 43 (transplant report)
355  NEB-2024-08-16288 R  46 (transplant report); request reads 40 (verify)
361  NEB-2024-08-16294 L               64 (request); 54 (transplant report)
478  NEB-2025-09-17530 R                 33 (request; transplant report 32)
481  NEB-2025-10-17533 R                 39 (request; transplant report 35)
567  NEB-2025-11-17625 L  68 (transplant report; request as read 64 - ve...
570  NEB-2025-11-17628 R        66 (transplant report; request 60 - verify)

    Recipient_Age_Clean
44                   21
84                   58
242                  35
275                  52
287                  58
291                  38
297                  19
322                  64
329                  56
347                  41
355                  60
361                  55
478                  62
481                  45
567                  60
570                  62

In [73]:
remaining_age_values = df.loc[
    df["Recipient_Age_Clean"].notna() &
    ~df["Recipient_Age_Clean"].astype(str).str.fullmatch(r"\d+(\.\d+)?"),
    ["Tissue_ID", "Recipient_Age", "Recipient_Age_Clean"]
]

print(remaining_age_values)

               Tissue_ID             Recipient_Age       Recipient_Age_Clean
12   NEB-2020-09-12665 L                   2 y 3 m                   2 y 3 m
18   NEB-2020-09-12671 L              60 (as read)              60 (as read)
23   NEB-2020-09-12676 L              72 (as read)              72 (as read)
28   NEB-2020-09-12681 L              18 (as read)              18 (as read)
34   NEB-2020-09-12687 L              13 (as read)              13 (as read)
37   NEB-2020-09-12690 L              67 (as read)              67 (as read)
73   NEB-2020-10-12728 L              30 (as read)              30 (as read)
79   NEB-2020-10-12734 L  9.5 (written "9 1/2 yr")  9.5 (written "9 1/2 yr")
104  NEB-2020-11-12806 R              60 (as read)              60 (as read)
124  NEB-2020-11-12829 R              71 (as read)              71 (as read)
284  NEB-2024-06-16115 L              31 (as read)              31 (as read)
443  NEB-2025-09-17495 R              17 (as read)              17 (as read)
444  NEB-2025-09-17496 L              81 (as read)              81 (as read)
449  NEB-2025-09-17501 R              21 (as read)              21 (as read)
468  NEB-2025-09-17520 R              84 (as read)              84 (as read)
474  NEB-2025-09-17526 L              17 (as read)              17 (as read)
484  NEB-2025-10-17536 L              21 (as read)              21 (as read)
486  NEB-2025-10-17539 L              61 (as read)              61 (as read)
491  NEB-2025-10-17544 L              36 (as read)              36 (as read)
495  NEB-2025-10-17548 L              40 (as read)              40 (as read)
549  NEB-2025-10-17604 R              54 (as read)              54 (as read)
551  NEB-2025-10-17606 R      8 (as read - verify)      8 (as read - verify)
559  NEB-2025-10-17616 L              38 (as read)              38 (as read)
572  NEB-2025-11-17630 L              65 (as read)              65 (as read)

In [74]:
import re
import pandas as pd

# Create cleaned age column from the original source column
df["Recipient_Age_Clean"] = df["Recipient_Age"]

# Manually verified recipient ages
verified_recipient_ages = {
    "NEB-2020-09-12697 L": 21,
    "NEB-2020-10-12739 L": 58,
    "NEB-2024-05-16072 L": 35,
    "NEB-2024-05-16105 R": 52,
    "NEB-2024-06-16118 L": 58,
    "NEB-2024-06-16122 R": 38,
    "NEB-2024-06-16128 L": 19,
    "NEB-2024-08-16255 R": 64,
    "NEB-2024-08-16262 L": 56,
    "NEB-2024-08-16280 R": 41,
    "NEB-2024-08-16288 R": 60,
    "NEB-2024-08-16294 L": 55,
    "NEB-2025-09-17530 R": 62,
    "NEB-2025-10-17533 R": 45,
    "NEB-2025-11-17625 L": 60,
    "NEB-2025-11-17628 R": 62,
    "NEB-2025-10-17606 R": 56,
}

# Apply manually verified ages
for tissue_id, age in verified_recipient_ages.items():
    df.loc[
        df["Tissue_ID"] == tissue_id,
        "Recipient_Age_Clean"
    ] = age


def clean_recipient_age(value):
    if pd.isna(value):
        return pd.NA

    value = str(value).strip()

    # Dataset notation:
    # "2 y 3 m" -> 23
    # "3 y 5 m" -> 35
    match = re.fullmatch(r"(\d+)\s*y\s*(\d+)\s*m.*", value)
    if match:
        return float(match.group(1) + match.group(2))

    # Extract first numeric value from straightforward annotations
    match = re.search(r"\d+(?:\.\d+)?", value)

    if match:
        return float(match.group())

    return pd.NA


# Clean values that were not manually verified
for idx in df.index:
    tissue_id = df.loc[idx, "Tissue_ID"]

    if tissue_id not in verified_recipient_ages:
        df.loc[idx, "Recipient_Age_Clean"] = clean_recipient_age(
            df.loc[idx, "Recipient_Age"]
        )


# 12734 L was not verified, so do not use the reported 9.5
df.loc[
    df["Tissue_ID"] == "NEB-2020-10-12734 L",
    "Recipient_Age_Clean"
] = pd.NA

# 17606 R was manually verified as 56
df.loc[
    df["Tissue_ID"] == "NEB-2025-10-17606 R",
    "Recipient_Age_Clean"
] = 56

In [77]:
print(df.loc[
    df["Recipient_Age_Clean"].notna() &
    ~df["Recipient_Age_Clean"].astype(str).str.fullmatch(r"\d+(\.\d+)?"),
    ["Tissue_ID", "Recipient_Age", "Recipient_Age_Clean"]
])

Empty DataFrame
Columns: [Tissue_ID, Recipient_Age, Recipient_Age_Clean]
Index: []

In [76]:
df.loc[
    df["Tissue_ID"].isin([
        "NEB-2020-09-12665 L",
        "NEB-2020-10-12734 L",
        "NEB-2025-10-17606 R",
        "NEB-2025-11-17628 R"
    ]),
    ["Tissue_ID", "Recipient_Age", "Recipient_Age_Clean"]
]

,Tissue_ID,Recipient_Age,Recipient_Age_Clean
12,NEB-2020-09-12665 L,2 y 3 m,23.0
79,NEB-2020-10-12734 L,"9.5 (written ""9 1/2 yr"")",<NA>
551,NEB-2025-10-17606 R,8 (as read - verify),56
570,NEB-2025-11-17628 R,66 (transplant report; request 60 - verify),62

In [78]:
print(df["Recipient_Age_Clean"].describe())

count     295.0
unique     78.0
top        60.0
freq       13.0
Name: Recipient_Age_Clean, dtype: float64

In [79]:
df["Recipient_Age_Clean"] = pd.to_numeric(
    df["Recipient_Age_Clean"],
    errors="coerce"
)

In [80]:
df["Recipient_Age_Clean"].dtype

dtype('float64')

In [81]:
print(df["Recipient_Age_Clean"].describe())

count    295.000000
mean      49.047458
std       21.209141
min        4.000000
25%       29.000000
50%       53.000000
75%       67.000000
max       85.000000
Name: Recipient_Age_Clean, dtype: float64

In [82]:
clinical_cols = [
    "Epithelium_Findings",
    "Epithelium_Severity",
    "Stroma_Findings",
    "Stroma_Severity",
    "Descemet_Findings",
    "Descemet_Severity",
    "Endothelium_Findings",
    "Endothelium_Severity",
    "Disease_Label",
    "Disease_Severity",
    "Primary_COD"
]

for col in clinical_cols:
    print(f"\n--- {col} ---")
    print(df[col].dropna().value_counts().head(15))

--- Epithelium_Findings ---
Epithelium_Findings
Clear and intact                                                                                         37
Nothing ticked                                                                                           17
Clear and intact ("mild arcus" annotation)                                                               16
Clear and intact. Release form: mild arcus, no exposure, no haziness, no ED                              13
Clear and intact ("mild arcus" annotation). Release form: mild arcus, no exposure, no haziness, no ED     9
Release form: mild arcus, mild exposure, no haziness, mild ED                                             8
Clear and intact. Release form: no arcus, no exposure, no haziness, no ED                                 8
Clear and intact; exposure                                                                                7
Exposure                                                                                                  7
Exposure (mild). Release form: mild arcus, mild exposure, no haziness, no ED                              6
Exposure + superficial ED                                                                                 5
Clear and intact; mild arcus (written). Release form: mild arcus, no exposure, no haziness, no ED         5
Clear and intact ("arcus" annotation)                                                                     4
Nothing ticked. Release form: mild arcus, no exposure, no haziness, no ED                                 4
Exposure ("very mild")                                                                                    3
Name: count, dtype: int64

--- Epithelium_Severity ---
Epithelium_Severity
Mild                                          298
Moderate                                        9
Very mild                                       3
Mild (as read)                                  1
Mild/Moderate - both marked (verify)            1
Large ED                                        1
Mild (evaluation); deep exposure (release)      1
Name: count, dtype: int64

--- Stroma_Findings ---
Stroma_Findings
Clear; arcus; diameter of clear area 8 mm                                     18
Release form: clear & compact                                                 16
Arcus (mild); diameter of clear area 8.0 mm. Release form: no edema           15
Arcus; diameter of clear area 8 mm                                            14
Clear; arcus ("mild arcus"); diameter of clear area 8 mm                      12
Arcus; diameter of clear area 8.5 mm                                          12
Arcus (mild); diameter of clear area 8.0 mm                                   12
Clear; arcus; diameter of clear area 8.5 mm                                    9
Clear; compact; arcus; diameter of clear area 8 mm                             9
Clear; arcus ("mild arcus"); diameter of clear area 8.5 mm                     8
Clear; compact; arcus; diameter of clear area 9 mm                             8
Arcus; diameter of clear area 9 mm                                             7
Clear; arcus; diameter of clear area 8.5 mm. Release form: clear & compact     7
Clear; compact; arcus; diameter of clear area 8.5 mm                           6
Arcus; diameter of clear area 8.0 mm. Release form: clear & compact            6
Name: count, dtype: int64

--- Stroma_Severity ---
Stroma_Severity
Mild                             393
Moderate                          13
Very mild                          5
Mild (moderate crossed out)        1
Mild (release form)                1
Mild (evaluation form)             1
Mild / moderate (both marked)      1
Name: count, dtype: int64

--- Descemet_Findings ---
Descemet_Findings
Folds; relative number: mild                                     100
Folds                                                             96
Folds (mild) (release form: mild folds)                           49
Folds; relative number: mild (release form: mild folds)           45
Folds; relative number mild (release form: mild folds)            45
Folds (release form: mild folds)                                  30
Release form: mild folds                                          23
Folds (mild)                                                      23
Folds; relative number mild                                       21
Folds (mild); relative number mild                                20
Folds (mild); relative number mild (release form: mild folds)     14
Folds; relative number: several                                   12
Folds ("very mild")                                               11
Folds (moderate); relative number: several                         6
No folds or defects                                                4
Name: count, dtype: int64

--- Descemet_Severity ---
Descemet_Severity
Mild                                     516
Moderate                                  38
Very mild                                  6
Mild / moderate (both marked)              3
Mild (moderate crossed out)                1
Mild (as read)                             1
Mild (release form)                        1
Moderate (evaluation); mild (release)      1
Name: count, dtype: int64

--- Endothelium_Findings ---
Endothelium_Findings
Stress lines; central; few                                                         96
Stress lines; central; few (release form: few stress lines)                        78
Relative number of stress lines: few (release form: few stress lines)              61
Relative number of stress lines: few                                               52
Nothing ticked on evaluation form                                                  28
Stress lines; peripheral; few                                                      23
Release form: few stress lines                                                     21
Stress lines; peripheral; few (release form: few stress lines)                     19
Stress lines; central; few; cell drop-out mild                                      9
Stress lines; peripheral; cell drop-out mild                                        6
RBCs on endo: mild                                                                  6
Stress lines; central/peripheral; few                                               5
Stress lines; central; few; cell drop-out mild (release form: few stress lines)     5
Nothing ticked (release form: few stress lines)                                     5
Stress lines; few                                                                   4
Name: count, dtype: int64

--- Endothelium_Severity ---
Endothelium_Severity
Mild                            62
Mild (cell drop-out)            18
Moderate                         2
Mild (as read)                   1
Mild (RBCs on endo)              1
Moderate (RBCs on endo)          1
Mild (cell drop-out, debris)     1
Mild (cell drop-out, RBCs)       1
Name: count, dtype: int64

--- Disease_Label ---
Disease_Label
Normal                                                                   505
Folds                                                                    324
FECD; Polymorphism and pleomorphism; Low cell density                     88
Guttata                                                                   53
Guttata; Folds                                                            28
FECD; Polymorphism and pleomorphism; Low cell density; Folds              20
FECD; Polymorphism and pleomorphism; Low cell density; Guttata             8
Polymorphism and pleomorphism                                              5
Poor cornea                                                                5
Folds; Guttata                                                             3
FECD; Polymorphism and pleomorphism; Low cell density; Guttata; Folds      3
Guttata; FECD; Polymorphism and pleomorphism; Low cell density             2
FECD; Polymorphism and pleomorphism                                        2
Low cell density                                                           2
Folds; FECD; Polymorphism and pleomorphism; Low cell density               1
Name: count, dtype: int64

--- Disease_Severity ---
Disease_Severity
Mild        475
Moderate     56
Severe       14
Name: count, dtype: int64

--- Primary_COD ---
Primary_COD
Aspiration pneumonia                 19
Carcinoma of lung                    12
ICH                                  11
Hepatic encephalopathy               11
CLCD                                 11
Carcinoma of breast                  10
STEMI                                 9
Chronic liver cell disease (CLCD)     9
Carcinoma of oesophagus               8
Heart failure                         7
Myocardial infarction (MI)            6
Multi-organ failure                   6
End-stage renal failure (ESRF)        6
ESRF                                  6
CKD                                   5
Name: count, dtype: int64

In [83]:
clinical_cols = [
    "Epithelium_Findings",
    "Epithelium_Severity",
    "Stroma_Findings",
    "Stroma_Severity",
    "Descemet_Findings",
    "Descemet_Severity",
    "Endothelium_Findings",
    "Endothelium_Severity",
    "Disease_Label",
    "Disease_Severity",
    "Primary_COD"
]

clinical_missing = (
    df[clinical_cols]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

print(clinical_missing)

Endothelium_Severity    968
Epithelium_Severity     741
Stroma_Severity         640
Disease_Severity        510
Descemet_Severity       488
Endothelium_Findings    480
Primary_COD             474
Descemet_Findings       469
Epithelium_Findings     468
Stroma_Findings         467
Disease_Label             1
dtype: int64

In [84]:
clinical_feature_cols = [
    "Epithelium_Findings",
    "Stroma_Findings",
    "Descemet_Findings",
    "Endothelium_Findings",
]

missing_pattern = (
    df[clinical_feature_cols]
    .isna()
    .astype(int)
    .value_counts()
    .reset_index(name="Count")
)

print(missing_pattern)

   Epithelium_Findings  Stroma_Findings  Descemet_Findings  \
0                    0                0                  0
1                    1                1                  1
2                    0                0                  0
3                    0                0                  1
4                    1                0                  0
5                    0                0                  1

   Endothelium_Findings  Count
0                     0    573
1                     1    467
2                     1     12
3                     1      1
4                     0      1
5                     0      1

In [86]:
clinical_feature_cols = [
    "Epithelium_Findings",
    "Stroma_Findings",
    "Descemet_Findings",
    "Endothelium_Findings",
]

df["Clinical_Findings_Available"] = (
    df[clinical_feature_cols].notna().all(axis=1)
).astype(int)

print(df["Clinical_Findings_Available"].value_counts())

Clinical_Findings_Available
1    573
0    482
Name: count, dtype: int64

In [88]:
print(df["Endothelium_Findings"].value_counts(dropna=False).head(30))

Endothelium_Findings
NaN                                                                                               480
Stress lines; central; few                                                                         96
Stress lines; central; few (release form: few stress lines)                                        78
Relative number of stress lines: few (release form: few stress lines)                              61
Relative number of stress lines: few                                                               52
Nothing ticked on evaluation form                                                                  28
Stress lines; peripheral; few                                                                      23
Release form: few stress lines                                                                     21
Stress lines; peripheral; few (release form: few stress lines)                                     19
Stress lines; central; few; cell drop-out mild                                                      9
Stress lines; peripheral; cell drop-out mild                                                        6
RBCs on endo: mild                                                                                  6
Stress lines; central/peripheral; few                                                               5
Stress lines; central; few; cell drop-out mild (release form: few stress lines)                     5
Nothing ticked (release form: few stress lines)                                                     5
Stress lines; few                                                                                   4
Stress lines; peripheral; few; cell drop-out mild                                                   4
Cell drop-out mild                                                                                  4
No endothelium boxes ticked                                                                         4
Nothing ticked on evaluation form. Release form: few stress lines                                   4
Nothing ticked                                                                                      4
RBCs on endothelium                                                                                 3
No stress lines or defects                                                                          3
Stress lines; few; cell drop-out mild                                                               3
Stress lines; central; few; cell drop-out: mild (release form: few stress lines)                    3
Nothing ticked on evaluation form (release form: few stress lines)                                  3
Stress lines; central; few (as marked)                                                              3
Stress lines; central and peripheral; few; cell drop-out mild (release form: few stress lines)      3
Stress lines; central/peripheral; few; cell drop-out mild                                           2
Stress lines; central; cell drop-out mild                                                           2
Name: count, dtype: int64

In [89]:
df["Endothelium_Findings"].dropna().unique()

<StringArray>
[                                                                                                                                                    'Stress lines; central; few',
                                                                                                                                                  'Stress lines; peripheral; few',
                                                                                                                                                              'Stress lines; few',
                                                                                                                                          'Stress lines; central/peripheral; few',
                                                                                                                 'Stress lines; central/peripheral; cell drop-out mild (as read)',
                                                                                                                      'Stress lines; central/peripheral; few; cell drop-out mild',
                                                                                                                                           'Relative number of stress lines: few',
                                                                                                                                 'Stress lines; central; few; cell drop-out mild',
                                                                                                                                   'Stress lines; peripheral; cell drop-out mild',
                                                                                                                              'Stress lines; peripheral; few; cell drop-out mild',
 ...
                                                                                           'Stress lines; peripheral; relative number of stress lines ticked (few circle struck)',
                                                                                                                                  'Stress lines; peripheral; relative number few',
 '"No stress lines" and "stress lines" boxes both marked; central and peripheral; few (crossed) and several marked; cell drop-out mild (release form: few stress lines) - verify',
                                                                                                         'Stress lines; few; cell drop-out mild (release form: few stress lines)',
                                                                                                  'Stress lines; central/peripheral marked; few; cell drop-out mild; debris mild',
                                                                      'Stress lines; central and peripheral; few; cell drop-out mild; RBCs mild (release form: few stress lines)',
                                                                                              'Stress lines; central; few; other comments RBC++ (release form: few stress lines)',
                                                                                                                                'Stress lines; central; few; other comments RBC+',
                                                                                                                                                                 'Nothing ticked',
                                                                                                                       'Stress lines; central; few; other comments: mild icteric']
Length: 124, dtype: str

In [90]:
for col in [
    "Descemet_Findings",
    "Stroma_Findings",
    "Epithelium_Findings"
]:
    print(f"\n{col}: {df[col].dropna().nunique()} unique non-null values")

Descemet_Findings: 77 unique non-null values

Stroma_Findings: 306 unique non-null values

Epithelium_Findings: 410 unique non-null values

In [91]:
df["Stroma_Findings"].dropna().unique()

<StringArray>
[                                                                                                      'Clear; arcus',
                                                                                                              'Arcus',
                                                                                 'Arcus; diameter of clear area 9 mm',
                                                           'Clear; arcus ("mild arcus"); diameter of clear area 8 mm',
                                                         'Clear; arcus ("mild arcus"); diameter of clear area 8.5 mm',
                                                                        'Clear; arcus; diameter of clear area 8.5 mm',
                                                     'Clear; arcus ("moderate arcus"); diameter of clear area 7.5 mm',
                                                                        'Clear; arcus; diameter of clear area 7.5 mm',
                                                                                 'Arcus; diameter of clear area 8 mm',
                                                                               'Arcus; diameter of clear area 7.5 mm',
 ...
                                                                     'Diameter of clear area 8 mm; scar - IOL marked',
                                'Clear; compact; arcus (mild); diameter of clear area 8.0 mm. Release form: no edema',
 'Clear; compact; arcus ("mild arcus" annotation); diameter of clear area 8.0 mm; scar - IOL. Release form: no edema',
                                         'Clear; arcus (mild); diameter of clear area 8.5 mm. Release form: no edema',
                       'Arcus (box ticked, level not circled); diameter of clear area 8.0 mm. Release form: no edema',
                                          'Clear; arcus (box ticked, level not circled); diameter of clear area 9 mm',
                                                                       'Clear; diameter of clear area as read 8.0 mm',
                                             'Clear; compact; diameter of clear area 8 mm; scar - IOL ("phaco scar")',
                                               'Clear; compact; arcus (mild, as read); diameter of clear area 8.5 mm',
                                               'Arcus (box ticked, level not circled); diameter of clear area 8.0 mm']
Length: 306, dtype: str

In [92]:
df["Epithelium_Findings"].dropna().unique()

<StringArray>
[                                                                                                                'Clear and intact',
                                                                                           'Exposure; peripheral ("mild exposure")',
                                                                                       'Other: small superficial epithelial defect',
                                                                                                   'Other: small epithelial defect',
                                                                                                          'Other: mild arcus noted',
                                                                   'Haze; exposure; location peripheral; mild ED ("mild exposure")',
                                                                              'Clear and intact; exposure; other: ED 1/3 (as read)',
                                                                                                       'Clear and intact; exposure',
                                                                                                                        'Other: ED',
                                                                       'Clear and intact; other: epithelial defect noted (as read)',
 ...
                                                      'Exposure (mild); location central and peripheral; other comments: eye lash+',
      'Clear and intact ("mild arcus" annotation); other comments: RBC+. Release form: mild arcus, no exposure, no haziness, no ED',
                            'Clear and intact ("scar [IOL]" annotation). Release form: mild arcus, no exposure, no haziness, no ED',
                                                                                 'Exposure (mild); other comments: superficial ED+',
                                                       'Exposure (mild). Release form: mild arcus, no exposure, no haziness, no ED',
                                                                   'Exposure (very mild); other comments: small ED near the limbus',
                           'Clear and intact and exposure (mild) both ticked; location central/peripheral; other comments: mild ED',
                                                             'Exposure (mild); location central/peripheral (blurred scan, as read)',
 'Nothing ticked; other comments: small ED near the limbus, eye lash+. Release form: mild arcus, no exposure, no haziness, mild ED',
                                                                        'Exposure (mild); other comments: small ED near the limbus']
Length: 410, dtype: str

In [94]:
print(pd.crosstab(
    df["Tissue_Grade_Clean"],
    df["Disease_Label"],
    margins=True
))

Disease_Label       FECD  FECD; Polymorphism and pleomorphism  \
Tissue_Grade_Clean
A                      0                                    0
A+                     1                                    0
B                      0                                    2
All                    1                                    2

Disease_Label       FECD; Polymorphism and pleomorphism; Low cell density  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                  88
All                                                                88

Disease_Label       FECD; Polymorphism and pleomorphism; Low cell density; Folds  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                  20
All                                                                20

Disease_Label       FECD; Polymorphism and pleomorphism; Low cell density; Guttata  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                   8
All                                                                 8

Disease_Label       FECD; Polymorphism and pleomorphism; Low cell density; Guttata; Folds  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                   3
All                                                                 3

Disease_Label       Folds  \
Tissue_Grade_Clean
A                     123
A+                    187
B                       8
All                   318

Disease_Label       Folds; FECD; Polymorphism and pleomorphism; Low cell density  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                   1
All                                                                 1

Disease_Label       Folds; Guttata  \
Tissue_Grade_Clean
A                                2
A+                               1
B                                0
All                              3

Disease_Label       Folds; Guttata; Polymorphism and pleomorphism  ...  \
Tissue_Grade_Clean                                                 ...
A                                                               0  ...
A+                                                              0  ...
B                                                               1  ...
All                                                             1  ...

Disease_Label       Guttata; FECD; Polymorphism and pleomorphism; Low cell density  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                   2
All                                                                 2

Disease_Label       Guttata; Folds  Low cell density  \
Tissue_Grade_Clean
A                               11                 2
A+                              17                 0
B                                0                 0
All                             28                 2

Disease_Label       Low cell density; Guttata  \
Tissue_Grade_Clean
A                                           1
A+                                          0
B                                           0
All                                         1

Disease_Label       Low cell density; Polymorphism and pleomorphism; FECD  \
Tissue_Grade_Clean
A                                                                   0
A+                                                                  0
B                                                                   1
All                                                                 1

Disease_Label       Normal  Polymorphism and pleomorphism  \
Tissue_Grade_Clean
A                      153                              4
A+                     312                              0
B                       29                              1
All                    494                              5

Disease_Label       Polymorphism and pleomorphism; Guttata; FECD  Poor cornea  \
Tissue_Grade_Clean
A                                                              0            0
A+                                                             0            0
B                                                              1            5
All                                                            1            5

Disease_Label        All
Tissue_Grade_Clean
A                    319
A+                   545
B                    172
All                 1036

[4 rows x 21 columns]

In [98]:
print(df["Disease_Label"].value_counts(dropna=False))

Disease_Label
Normal                                                                   505
Folds                                                                    324
FECD; Polymorphism and pleomorphism; Low cell density                     88
Guttata                                                                   53
Guttata; Folds                                                            28
FECD; Polymorphism and pleomorphism; Low cell density; Folds              20
FECD; Polymorphism and pleomorphism; Low cell density; Guttata             8
Polymorphism and pleomorphism                                              5
Poor cornea                                                                5
Folds; Guttata                                                             3
FECD; Polymorphism and pleomorphism; Low cell density; Guttata; Folds      3
Guttata; FECD; Polymorphism and pleomorphism; Low cell density             2
FECD; Polymorphism and pleomorphism                                        2
Low cell density                                                           2
Folds; FECD; Polymorphism and pleomorphism; Low cell density               1
FECD                                                                       1
Polymorphism and pleomorphism; Guttata; FECD                               1
Low cell density; Polymorphism and pleomorphism; FECD                      1
Folds; Guttata; Polymorphism and pleomorphism                              1
Low cell density; Guttata                                                  1
NaN                                                                        1
Name: count, dtype: int64

In [99]:
import re
import pandas as pd

def extract_clear_area_diameter(value):
    if pd.isna(value):
        return pd.NA

    match = re.search(
        r"diameter of clear area(?:\s+as read)?\s*(\d+(?:\.\d+)?)\s*mm",
        str(value),
        flags=re.IGNORECASE
    )

    if match:
        return float(match.group(1))

    return pd.NA


df["Stroma_Clear_Area_Diameter_mm"] = (
    df["Stroma_Findings"]
    .apply(extract_clear_area_diameter)
)

In [101]:
print(df["Stroma_Clear_Area_Diameter_mm"].describe())

count     555.0
unique     17.0
top         8.0
freq      239.0
Name: Stroma_Clear_Area_Diameter_mm, dtype: float64

In [103]:
print(df[
    ["Stroma_Findings", "Stroma_Clear_Area_Diameter_mm"]
].dropna(
    subset=["Stroma_Clear_Area_Diameter_mm"]
).head(20))

                                      Stroma_Findings  \
5                  Arcus; diameter of clear area 9 mm
6                  Arcus; diameter of clear area 9 mm
7   Clear; arcus ("mild arcus"); diameter of clear...
8   Clear; arcus ("mild arcus"); diameter of clear...
9   Clear; arcus ("mild arcus"); diameter of clear...
10        Clear; arcus; diameter of clear area 8.5 mm
11  Clear; arcus ("mild arcus"); diameter of clear...
12  Clear; arcus ("mild arcus"); diameter of clear...
13  Clear; arcus ("moderate arcus"); diameter of c...
14        Clear; arcus; diameter of clear area 7.5 mm
15                 Arcus; diameter of clear area 8 mm
16        Clear; arcus; diameter of clear area 7.5 mm
17        Clear; arcus; diameter of clear area 7.5 mm
18               Arcus; diameter of clear area 7.5 mm
20  Arcus ("mild arcus"); diameter of clear area 9 mm
21  Arcus ("mild arcus"); diameter of clear area 8 mm
22  Arcus ("mild arcus"); diameter of clear area 8 mm
23  Diameter of clear area 8 mm (no stromal box ti...
24  Diameter of clear area 8 mm (no stromal box ti...
25    Arcus; scar: phaco; diameter of clear area 8 mm

   Stroma_Clear_Area_Diameter_mm
5                            9.0
6                            9.0
7                            8.0
8                            8.0
9                            8.5
10                           8.5
11                           8.5
12                           8.5
13                           7.5
14                           7.5
15                           8.0
16                           7.5
17                           7.5
18                           7.5
20                           9.0
21                           8.0
22                           8.0
23                           8.0
24                           8.0
25                           8.0

In [104]:
df["Stroma_Clear_Area_Diameter_mm"] = pd.to_numeric(
    df["Stroma_Clear_Area_Diameter_mm"],
    errors="coerce"
)

In [106]:
print(df["Stroma_Clear_Area_Diameter_mm"].describe())

count    555.000000
mean       8.417748
std        0.571562
min        6.000000
25%        8.000000
50%        8.500000
75%        9.000000
max       10.000000
Name: Stroma_Clear_Area_Diameter_mm, dtype: float64

In [107]:
def has_text(value, pattern):
    if pd.isna(value):
        return pd.NA
    return bool(re.search(pattern, str(value), flags=re.IGNORECASE))


df["Stroma_Is_Clear"] = df["Stroma_Findings"].apply(
    lambda x: has_text(x, r"\bclear\b")
)

df["Stroma_Is_Compact"] = df["Stroma_Findings"].apply(
    lambda x: has_text(x, r"\bcompact\b")
)

df["Stroma_Has_Arcus"] = df["Stroma_Findings"].apply(
    lambda x: has_text(x, r"\barcus\b")
)

df["Stroma_Has_Edema"] = df["Stroma_Findings"].apply(
    lambda x: has_text(x, r"\bedema\b")
)

df["Stroma_Has_Scar"] = df["Stroma_Findings"].apply(
    lambda x: has_text(x, r"\bscar\b")
)

In [109]:
print(df[
    [
        "Stroma_Is_Clear",
        "Stroma_Is_Compact",
        "Stroma_Has_Arcus",
        "Stroma_Has_Edema",
        "Stroma_Has_Scar"
    ]
].value_counts(dropna=False))

Stroma_Is_Clear  Stroma_Is_Compact  Stroma_Has_Arcus  Stroma_Has_Edema  Stroma_Has_Scar
NaN              NaN                NaN               NaN               NaN                467
True             False              True              False             False              214
                 True               True              False             False              146
                 False              True              True              False               74
                 True               False             False             False               46
                 False              False             False             False               29
                 True               True              True              False               25
                 False              True              False             True                13
                                    False             True              False                7
False            False              False             True              False                6
True             False              True              True              True                 5
                 True               False             False             True                 4
False            False              True              False             False                3
True             False              False             False             True                 3
                 True               True              True              True                 3
                                                      False             True                 3
                                    False             True              False                3
False            False              False             False             False                2
True             False              False             True              True                 2
Name: count, dtype: int64

In [110]:
def detect_edema(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if re.search(r"\bno\s+edema\b", text):
        return False

    if re.search(r"\bedema\b", text):
        return True

    return False


df["Stroma_Has_Edema"] = df["Stroma_Findings"].apply(detect_edema)

In [112]:
print(df["Stroma_Has_Edema"].value_counts(dropna=False))

Stroma_Has_Edema
False    578
<NA>     467
True      10
Name: count, dtype: int64

In [113]:
def extract_arcus_severity(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "arcus" not in text:
        return "None"

    if "moderate arcus" in text:
        return "Moderate"

    if "mild arcus" in text:
        return "Mild"

    if "level not circled" in text:
        return "Unspecified"

    return "Unspecified"


df["Stroma_Arcus_Severity"] = df["Stroma_Findings"].apply(
    extract_arcus_severity
)

In [115]:
print(df["Stroma_Arcus_Severity"].value_counts(dropna=False))

Stroma_Arcus_Severity
NaN            467
Unspecified    437
None           102
Mild            43
Moderate         6
Name: count, dtype: int64

In [116]:
df["Stroma_Scar_Type"] = pd.NA

mask = df["Stroma_Findings"].notna()

df.loc[
    mask & df["Stroma_Findings"].str.contains(
        "phaco scar", case=False, na=False
    ),
    "Stroma_Scar_Type"
] = "Phaco scar"

df.loc[
    mask
    & df["Stroma_Scar_Type"].isna()
    & df["Stroma_Findings"].str.contains(
        r"\bscar\b", case=False, na=False
    ),
    "Stroma_Scar_Type"
] = "Other scar"

df.loc[
    mask & df["Stroma_Scar_Type"].isna(),
    "Stroma_Scar_Type"
] = "None"

In [117]:
print(df["Stroma_Scar_Type"].value_counts(dropna=False))

Stroma_Scar_Type
None          555
<NA>          467
Other scar     27
Phaco scar      6
Name: count, dtype: int64

In [118]:
df["Descemet_Findings"].dropna().unique()

<StringArray>
[                                                                                'Folds',
                                                                   'Folds ("very mild")',
                                                       'Folds; relative number: several',
                                                 'Folds (mild and moderate both marked)',
                                                          'Folds; relative number: mild',
                                                    'Folds ("no folds" box also marked)',
                                    'Folds; relative number: several (mild overwritten)',
                                                  'Folds (mild struck, moderate ticked)',
                                              'Folds (box struck; mild marked - verify)',
                           'Folds (box struck through - as read); relative number: mild',
                                                                   'No folds or defects',
                             'Mild marked (folds box not ticked); relative number: mild',
                                                           'Mild (folds box not ticked)',
                                                       'Folds (severity mark ambiguous)',
                                    '"No folds" and "Folds" bracketed together - verify',
                                                    'Mild marked (folds box not ticked)',
                                                                           'Folds (Nil)',
                                                      'Folds (release form: mild folds)',
                                                              'No Descemet boxes ticked',
                                                                       'Folds (as read)',
                                                              'Release form: mild folds',
                                                 'Folds ("no folds" box struck through)',
                               'Folds; relative number: mild (release form: mild folds)',
                       'Folds ("no folds" box struck through; release form: mild folds)',
                        'Folds; relative number: several (release form: moderate folds)',
                          'Folds ("no folds" box struck through); relative number: mild',
                           'Nothing ticked on evaluation form. Release form: mild folds',
                                                                        'Nothing ticked',
                                 'Folds; relative number: mild (release form: no folds)',
                                        'Folds ("very mild") (release form: mild folds)',
                                                  'Folds (release form: moderate folds)',
                                            'Folds (moderate); relative number: several',
                                                                          'Folds (mild)',
                                          'No folds or defects (release form: no folds)',
                                               'Folds (mild) (release form: mild folds)',
                         'Folds (mild); relative number mild (release form: mild folds)',
                            'Mild / relative number mild circled (Folds box not ticked)',
                                             'Nothing ticked (release form: mild folds)',
                                                                      'Nothing recorded',
                                          'Folds (very mild) (release form: mild folds)',
                                                    'Folds (mild); relative number mild',
                                                            'Folds (no severity marked)',
                                                                   'Folds ("very" mild)',
                                          'Folds (mild) (release form: very mild folds)',
                                'Folds; relative number mild (release form: mild folds)',
                                                'Folds; mild (release form: mild folds)',
                'Relative number mild (Folds box not ticked) (release form: mild folds)',
                                                   'Mild / relative number mild circled',
                                                           'Folds; relative number mild',
                                                             'Mild folds (release form)',
                       'Relative number of folds marked mild (release form: mild folds)',
                                               'Folds; relative number mild (as marked)',
                               'Folds; relative number mild (marked but box not ticked)',
                                                  'Folds; relative number mild (marked)',
             'Folds (moderate); relative number: several (release form: moderate folds)',
                                     'Folds (very mild) (release form: very mild folds)',
                                                                     'Folds (very mild)',
                                           'Folds (moderate) (release form: mild folds)',
                                         'Folds; relative number: mild (box not ticked)',
                                       'Folds (moderate) (release form: moderate folds)',
                        'Folds (mild); relative number: mild (release form: mild folds)',
                                         'Folds; very mild ("very" written beside mild)',
                                      'Folds; very mild (release form: very mild folds)',
                                             'No folds or defects ("Folds: NO" written)',
                                                      'Folds (mild) ("no folds" struck)',
                                'Folds mild marked (box unticked); relative number mild',
                           'Folds mild marked (box unticked) (release form: mild folds)',
                                                 'Folds (mild); relative number several',
            'Folds (mild and moderate both marked - as read) (release form: mild folds)',
 'Mild / relative number mild circled (Folds box not ticked) (release form: mild folds)',
                            'Folds; relative number moderate (release form: mild folds)',
                    'Folds; relative number several/moderate (release form: mild folds)',
                         'Folds/no-folds boxes not ticked (only severity "mild" marked)',
           'Folds; relative number mild, written "very" mild (release form: mild folds)',
                     'Folds (mild); relative number: several (release form: mild folds)',
                           'Folds (mild) ("no folds" struck) (release form: mild folds)',
                 'Folds (moderate); relative number: several (release form: mild folds)']
Length: 77, dtype: str

In [120]:
def detect_descemet_review(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    review_terms = [
        "verify",
        "ambiguous",
        "both marked",
        "both ticked",
        "struck",
        "not ticked",
        "box not ticked",
        "box unticked",
    ]

    if any(term in text for term in review_terms):
        return True

    if "no folds" in text and "folds" in text:
        return True

    return False


df["Descemet_Review_Flag"] = df["Descemet_Findings"].apply(
    detect_descemet_review
)

In [122]:
print(df["Descemet_Review_Flag"].value_counts(dropna=False))

Descemet_Review_Flag
False    544
<NA>     469
True      42
Name: count, dtype: int64

In [123]:
def detect_folds(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    # Explicit negative finding
    if "no folds" in text and "folds" not in text.replace("no folds", ""):
        return False

    # Explicit positive finding
    if "folds" in text:
        return True

    # Severity marked but folds box not ticked
    if "folds box not ticked" in text or "folds box not ticked" in text:
        return False

    return False


df["Descemet_Has_Folds"] = df["Descemet_Findings"].apply(detect_folds)

In [124]:
df.loc[
    df["Descemet_Review_Flag"] == True,
    "Descemet_Has_Folds"
] = pd.NA

In [125]:
print(df["Descemet_Has_Folds"].value_counts(dropna=False))

Descemet_Has_Folds
True     535
<NA>     511
False      9
Name: count, dtype: int64

In [126]:
def extract_fold_severity(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()
    if "verify" in text or "ambiguous" in text:
        return pd.NA

    if "moderate" in text:
        return "Moderate"

    if "very mild" in text:
        return "Very mild"

    if "mild" in text:
        return "Mild"

    return "Unspecified"


df["Descemet_Fold_Severity"] = df["Descemet_Findings"].apply(
    extract_fold_severity
)

df.loc[
    df["Descemet_Review_Flag"] == True,
    "Descemet_Fold_Severity"
] = pd.NA

In [128]:
print(df["Descemet_Fold_Severity"].value_counts(dropna=False))

Descemet_Fold_Severity
NaN            511
Mild           387
Unspecified    118
Moderate        21
Very mild       18
Name: count, dtype: int64

In [129]:
def extract_fold_relative_number(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "relative number" not in text:
        return "Unspecified"

    if "several/moderate" in text:
        return "Several/Moderate"

    if "several" in text:
        return "Several"

    if "moderate" in text:
        return "Moderate"

    if "mild" in text:
        return "Mild"

    return "Unspecified"


df["Descemet_Fold_Relative_Number"] = (
    df["Descemet_Findings"]
    .apply(extract_fold_relative_number)
)

df.loc[
    df["Descemet_Review_Flag"] == True,
    "Descemet_Fold_Relative_Number"
] = pd.NA

In [131]:
print(df["Descemet_Fold_Relative_Number"].value_counts(dropna=False))

Descemet_Fold_Relative_Number
NaN                 511
Unspecified         261
Mild                252
Several              28
Moderate              2
Several/Moderate      1
Name: count, dtype: int64

In [133]:
df["Endo_Has_Stress_Lines"] = df["Endothelium_Findings"].apply(
    lambda x: (
        pd.NA if pd.isna(x)
        else (
            False
            if re.search(r"no stress lines", str(x), flags=re.IGNORECASE)
            else bool(re.search(r"stress lines", str(x), flags=re.IGNORECASE))
        )
    )
)

print(df["Endo_Has_Stress_Lines"].value_counts(dropna=False))

Endo_Has_Stress_Lines
True     499
<NA>     480
False     76
Name: count, dtype: int64

In [134]:
def extract_stress_line_location(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "stress lines" not in text:
        return "None"

    if "central/peripheral" in text or "central and peripheral" in text:
        return "Central + Peripheral"

    if "central" in text:
        return "Central"

    if "peripheral" in text:
        return "Peripheral"

    return "Unspecified"


df["Endo_Stress_Line_Location"] = (
    df["Endothelium_Findings"]
    .apply(extract_stress_line_location)
)

In [136]:
print(df["Endo_Stress_Line_Location"].value_counts(dropna=False))

Endo_Stress_Line_Location
NaN                     480
Central                 243
Unspecified             174
Peripheral               67
None                     63
Central + Peripheral     28
Name: count, dtype: int64

In [137]:
def extract_stress_line_amount(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "no stress lines" in text:
        return "None"

    if "stress lines" not in text:
        return "None"

    if "several" in text:
        return "Several"

    if "few" in text:
        return "Few"

    return "Unspecified"


df["Endo_Stress_Line_Amount"] = (
    df["Endothelium_Findings"]
    .apply(extract_stress_line_amount)
)

In [138]:
print(df["Endo_Stress_Line_Amount"].value_counts(dropna=False))

Endo_Stress_Line_Amount
NaN            480
Few            479
None            76
Unspecified     18
Several          2
Name: count, dtype: int64

In [139]:
def detect_cell_dropout(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    return bool(
        re.search(r"cell\s*drop[- ]?out", text)
    )


df["Endo_Has_Cell_Dropout"] = (
    df["Endothelium_Findings"]
    .apply(detect_cell_dropout)
)

In [140]:
print(df["Endo_Has_Cell_Dropout"].value_counts(dropna=False))

Endo_Has_Cell_Dropout
False    482
<NA>     480
True      93
Name: count, dtype: int64

In [141]:
def detect_rbc(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    return bool(re.search(r"\brbc", text))


df["Endo_Has_RBC"] = (
    df["Endothelium_Findings"]
    .apply(detect_rbc)
)

In [143]:
print(df["Endo_Has_RBC"].value_counts(dropna=False))

Endo_Has_RBC
False    545
<NA>     480
True      30
Name: count, dtype: int64

In [144]:
def extract_rbc_severity(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "rbc++" in text:
        return "++"

    if "rbc+" in text:
        return "+"

    if re.search(r"rbc[^a-z]*(mild)", text):
        return "Mild"

    if "rbc" in text:
        return "Unspecified"

    return "None"


df["Endo_RBC_Severity"] = (
    df["Endothelium_Findings"]
    .apply(extract_rbc_severity)
)

In [145]:
print(df["Endo_RBC_Severity"].value_counts(dropna=False))

Endo_RBC_Severity
None           545
NaN            480
Unspecified     22
+                6
++               2
Name: count, dtype: int64

In [146]:
def extract_cell_dropout_severity(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "cell drop" not in text:
        return "None"

    if "moderate" in text:
        return "Moderate"

    if "mild" in text:
        return "Mild"

    return "Unspecified"


df["Endo_Cell_Dropout_Severity"] = (
    df["Endothelium_Findings"]
    .apply(extract_cell_dropout_severity)
)

In [147]:
print(df["Endo_Cell_Dropout_Severity"].value_counts(dropna=False))

Endo_Cell_Dropout_Severity
None        482
NaN         480
Mild         90
Moderate      3
Name: count, dtype: int64

In [148]:
endo_features = [
    "Endo_Has_Stress_Lines",
    "Endo_Stress_Line_Location",
    "Endo_Stress_Line_Amount",
    "Endo_Has_Cell_Dropout",
    "Endo_Cell_Dropout_Severity",
    "Endo_Has_RBC",
    "Endo_RBC_Severity",
]

df[endo_features].describe(include="all").T

                           count unique      top freq
Endo_Has_Stress_Lines        575      2     True  499
Endo_Stress_Line_Location    575      5  Central  243
Endo_Stress_Line_Amount      575      4      Few  479
Endo_Has_Cell_Dropout        575      2    False  482
Endo_Cell_Dropout_Severity   575      3     None  482
Endo_Has_RBC                 575      2    False  545
Endo_RBC_Severity            575      4     None  545

In [149]:
for col in endo_features:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Endo_Has_Stress_Lines ---
Endo_Has_Stress_Lines
True     499
<NA>     480
False     76
Name: count, dtype: int64

--- Endo_Stress_Line_Location ---
Endo_Stress_Line_Location
NaN                     480
Central                 243
Unspecified             174
Peripheral               67
None                     63
Central + Peripheral     28
Name: count, dtype: int64

--- Endo_Stress_Line_Amount ---
Endo_Stress_Line_Amount
NaN            480
Few            479
None            76
Unspecified     18
Several          2
Name: count, dtype: int64

--- Endo_Has_Cell_Dropout ---
Endo_Has_Cell_Dropout
False    482
<NA>     480
True      93
Name: count, dtype: int64

--- Endo_Cell_Dropout_Severity ---
Endo_Cell_Dropout_Severity
None        482
NaN         480
Mild         90
Moderate      3
Name: count, dtype: int64

--- Endo_Has_RBC ---
Endo_Has_RBC
False    545
<NA>     480
True      30
Name: count, dtype: int64

--- Endo_RBC_Severity ---
Endo_RBC_Severity
None           545
NaN            480
Unspecified     22
+                6
++               2
Name: count, dtype: int64

In [150]:
def detect_exposure(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    # Explicit negative
    if re.search(r"\bno exposure\b", text):
        return False

    if "exposure" in text:
        return True

    return False


df["Epi_Has_Exposure"] = (
    df["Epithelium_Findings"]
    .apply(detect_exposure)
)

In [152]:
print(df["Epi_Has_Exposure"].value_counts(dropna=False))

Epi_Has_Exposure
<NA>     468
True     316
False    271
Name: count, dtype: int64

In [153]:
def extract_exposure_severity(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "no exposure" in text:
        return "None"

    if "very mild" in text and "exposure" in text:
        return "Very mild"

    if "mild exposure" in text:
        return "Mild"

    if "exposure" in text:
        return "Unspecified"

    return "None"


df["Epi_Exposure_Severity"] = (
    df["Epithelium_Findings"]
    .apply(extract_exposure_severity)
)

In [155]:
print(df["Epi_Exposure_Severity"].value_counts(dropna=False))

Epi_Exposure_Severity
NaN            468
None           271
Mild           157
Unspecified    142
Very mild       17
Name: count, dtype: int64

In [157]:
def detect_epithelial_defect(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if re.search(r"\bno\s+(epithelial\s+)?defect\b", text):
        return False

    if re.search(r"\b(epithelial\s+)?defect\b", text):
        return True

    return False


df["Epi_Has_Defect"] = df["Epithelium_Findings"].apply(
    detect_epithelial_defect
)

print(df["Epi_Has_Defect"].value_counts(dropna=False))

Epi_Has_Defect
False    583
<NA>     468
True       4
Name: count, dtype: int64

In [159]:
print(df.loc[
    df["Epi_Has_Defect"] == True,
    ["Tissue_ID", "Epithelium_Findings"]
])

              Tissue_ID                                Epithelium_Findings
5   NEB-2020-09-12658 R         Other: small superficial epithelial defect
6   NEB-2020-09-12659 L                     Other: small epithelial defect
18  NEB-2020-09-12671 L  Clear and intact; other: epithelial defect not...
19  NEB-2020-09-12672 R                      Other: ED (epithelial defect)

In [161]:
def detect_haze(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if re.search(r"\bno\s+haze\b", text):
        return False

    if re.search(r"\bhaze\b", text):
        return True

    return False


df["Epi_Has_Haze"] = df["Epithelium_Findings"].apply(
    detect_haze
)

print(df["Epi_Has_Haze"].value_counts(dropna=False))

Epi_Has_Haze
False    555
<NA>     468
True      32
Name: count, dtype: int64

In [163]:
print(df.loc[
    df["Epi_Has_Haze"] == True,
    ["Tissue_ID", "Epithelium_Findings"]
])

               Tissue_ID                                Epithelium_Findings
11   NEB-2020-09-12664 R  Haze; exposure; location peripheral; mild ED (...
29   NEB-2020-09-12682 R  Haze; exposure; other: superficial ED on the e...
51   NEB-2020-09-12704 L  Haze; exposure; location peripheral ("mild exp...
52   NEB-2020-09-12705 R  Haze; exposure; location peripheral; other: ED...
53   NEB-2020-10-12706 R                                  Haze; other: RBC+
54   NEB-2020-10-12707 L                             Haze; other: ED+, RBC+
79   NEB-2020-10-12734 L  Clear and intact; haze; exposure; location per...
97   NEB-2020-10-12761 R  Haze (mild); exposure (moderate); location cen...
99   NEB-2020-10-12772 L  Haze (very mild); exposure; peripheral ("ptery...
106  NEB-2020-11-12808 L  Clear and intact (stroke also crosses Haze box...
121  NEB-2020-11-12826 R                                               Haze
122  NEB-2020-11-12827 L                                               Haze
148  NEB-2021-02-12988 L  Haze; exposure; location peripheral; other: su...
149  NEB-2021-02-12989 R  Haze; exposure; location peripheral; other: su...
164  NEB-2022-04-13848 R  Haze; exposure ("CN" as read); other: superfic...
169  NEB-2022-09-14223 R  Haze; exposure; location peripheral; other: mi...
170  NEB-2022-09-14224 L  Haze; exposure; location peripheral; other: RB...
171  NEB-2022-09-14229 L  Haze; exposure (diffuse also marked); other: s...
172  NEB-2022-09-14230 R             Haze; exposure; other: superficial ED+
191  NEB-2022-10-14318 R  Haze box marked (as read); other: mild ED ("ex...
288  NEB-2024-06-16119 R  Clear and intact and haze boxes both marked (a...
295  NEB-2024-06-16126 R  Clear and intact (haze box also marked - as re...
312  NEB-2024-06-16143 L  Clear and intact (Haze box also marked - verif...
344  NEB-2024-08-16277 L  Haze/exposure boxes ticked (as read); exposure...
356  NEB-2024-08-16289 L  Haze/exposure boxes ticked; exposure mild; loc...
420  NEB-2025-09-17472 L  Haze (mild) ("senile haze" annotation as read)...
421  NEB-2025-09-17473 R  Haze (mild) ("senile arcus" annotation as read...
441  NEB-2025-09-17493 R                Haze box marked (level not circled)
450  NEB-2025-09-17502 L  Haze and Exposure boxes ticked; mild. Release ...
503  NEB-2025-10-17556 R  Haze; mild. Exposure; mild; other comments: su...
512  NEB-2025-10-17566 L  Haze ticked; exposure mild. Release form: mild...
513  NEB-2025-10-17567 R  Haze ticked; exposure mild. Release form: mild...

In [165]:
def extract_haze_severity(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "no haze" in text:
        return "None"

    if "very mild" in text and "haze" in text:
        return "Very mild"

    if re.search(r"haze\s*\(\s*mild\s*\)", text):
        return "Mild"

    if re.search(r"\bhaze\b[^;,.]*(?:[: ]|is )mild", text):
        return "Mild"

    if "haze" in text:
        return "Unspecified"

    return "None"


df["Epi_Haze_Severity"] = (
    df["Epithelium_Findings"]
    .apply(extract_haze_severity)
)

print(df["Epi_Haze_Severity"].value_counts(dropna=False))

Epi_Haze_Severity
None           555
NaN            468
Unspecified     28
Mild             3
Very mild        1
Name: count, dtype: int64

In [167]:
def extract_exposure_location(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    if "exposure" not in text:
        return "None"

    if "central/peripheral" in text or "central and peripheral" in text:
        return "Central + Peripheral"

    if "central" in text:
        return "Central"

    if "peripheral" in text:
        return "Peripheral"

    return "Unspecified"


df["Epi_Exposure_Location"] = (
    df["Epithelium_Findings"]
    .apply(extract_exposure_location)
)

print(df["Epi_Exposure_Location"].value_counts(dropna=False))

Epi_Exposure_Location
NaN                     468
Unspecified             266
None                    164
Peripheral               97
Central                  31
Central + Peripheral     29
Name: count, dtype: int64

In [168]:
def extract_exposure_location(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).lower()

    # Explicitly no exposure
    if re.search(r"\bno\s+exposure\b", text):
        return "None"

    # No exposure mentioned
    if "exposure" not in text:
        return "None"

    if "central/peripheral" in text or "central and peripheral" in text:
        return "Central + Peripheral"

    if "central" in text and "peripheral" in text:
        return "Central + Peripheral"

    if "central" in text:
        return "Central"

    if "peripheral" in text:
        return "Peripheral"

    return "Unspecified"


df["Epi_Exposure_Location"] = (
    df["Epithelium_Findings"]
    .apply(extract_exposure_location)
)

df["Epi_Exposure_Location"].value_counts(dropna=False)

Epi_Exposure_Location
NaN                     468
None                    271
Unspecified             159
Peripheral               97
Central + Peripheral     53
Central                   7
Name: count, dtype: int64

In [170]:
print(pd.crosstab(
    df["Epi_Has_Exposure"],
    df["Epi_Exposure_Location"],
    dropna=False
))

Epi_Exposure_Location  Central  Central + Peripheral  None  Peripheral  \
Epi_Has_Exposure
NaN                          0                     0     0           0
False                        0                     0   271           0
True                         7                    53     0          97

Epi_Exposure_Location  Unspecified  NaN
Epi_Has_Exposure
NaN                              0  468
False                            0    0
True                           159    0

In [172]:
df["Epi_Has_Arcus"] = df["Epithelium_Findings"].apply(
    lambda x: (
        pd.NA
        if pd.isna(x)
        else bool(re.search(r"\barcus\b", str(x), flags=re.IGNORECASE))
    )
)

print(df["Epi_Has_Arcus"].value_counts(dropna=False))

Epi_Has_Arcus
<NA>     468
True     328
False    259
Name: count, dtype: int64

In [174]:
print(df.loc[
    df["Epithelium_Findings"].notna(),
    "Epithelium_Findings"
].value_counts().head(30))

Epithelium_Findings
Clear and intact                                                                                         37
Nothing ticked                                                                                           17
Clear and intact ("mild arcus" annotation)                                                               16
Clear and intact. Release form: mild arcus, no exposure, no haziness, no ED                              13
Clear and intact ("mild arcus" annotation). Release form: mild arcus, no exposure, no haziness, no ED     9
Release form: mild arcus, mild exposure, no haziness, mild ED                                             8
Clear and intact. Release form: no arcus, no exposure, no haziness, no ED                                 8
Clear and intact; exposure                                                                                7
Exposure                                                                                                  7
Exposure (mild). Release form: mild arcus, mild exposure, no haziness, no ED                              6
Exposure + superficial ED                                                                                 5
Clear and intact; mild arcus (written). Release form: mild arcus, no exposure, no haziness, no ED         5
Clear and intact ("arcus" annotation)                                                                     4
Nothing ticked. Release form: mild arcus, no exposure, no haziness, no ED                                 4
Exposure ("very mild")                                                                                    3
Exposure (mild)                                                                                           3
Clear and intact; mild arcus (written)                                                                    3
Nothing ticked; other comments: mild ED                                                                   3
Exposure; peripheral; other: superficial ED+                                                              2
Clear and intact; other: mild ED+                                                                         2
Clear and intact; exposure; peripheral ("mild exposure+")                                                 2
Clear and intact; exposure (NO)                                                                           2
Clear and intact; other: ED+                                                                              2
Clear and intact; other: one eyelash+                                                                     2
"Mild ED" (ED marked on diagram; no boxes ticked)                                                         2
Haze                                                                                                      2
Clear and intact; exposure; location peripheral ("exposure +")                                            2
Clear and intact; "mild ED+"                                                                              2
Exposure; location central + peripheral                                                                   2
Haze; exposure; location peripheral; other: superficial ED+, eye lash+                                    2
Name: count, dtype: int64

In [175]:
epi_features = [
    "Epi_Has_Exposure",
    "Epi_Exposure_Severity",
    "Epi_Exposure_Location",
    "Epi_Has_Defect",
    "Epi_Has_Haze",
    "Epi_Haze_Severity",
    "Epi_Has_Arcus",
]

df[epi_features].info()

<class 'pandas.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Epi_Has_Exposure       587 non-null    object
 1   Epi_Exposure_Severity  587 non-null    str
 2   Epi_Exposure_Location  587 non-null    str
 3   Epi_Has_Defect         587 non-null    object
 4   Epi_Has_Haze           587 non-null    object
 5   Epi_Haze_Severity      587 non-null    str
 6   Epi_Has_Arcus          587 non-null    object
dtypes: object(4), str(3)
memory usage: 57.8+ KB

In [177]:
print(df[epi_features].isna().sum())

Epi_Has_Exposure         468
Epi_Exposure_Severity    468
Epi_Exposure_Location    468
Epi_Has_Defect           468
Epi_Has_Haze             468
Epi_Haze_Severity        468
Epi_Has_Arcus            468
dtype: int64

In [179]:
stroma_features = [
    "Stroma_Clear_Area_Diameter_mm",
    "Stroma_Is_Clear",
    "Stroma_Is_Compact",
    "Stroma_Has_Arcus",
    "Stroma_Has_Edema",
    "Stroma_Arcus_Severity",
    "Stroma_Scar_Type",
]

print(df[stroma_features].isna().sum())

Stroma_Clear_Area_Diameter_mm    500
Stroma_Is_Clear                  467
Stroma_Is_Compact                467
Stroma_Has_Arcus                 467
Stroma_Has_Edema                 467
Stroma_Arcus_Severity            467
Stroma_Scar_Type                 467
dtype: int64

In [182]:
print(df.loc[
    df["Stroma_Clear_Area_Diameter_mm"].notna(),
    ["Tissue_ID", "Stroma_Findings", "Stroma_Clear_Area_Diameter_mm"]
].head(20))

              Tissue_ID                                    Stroma_Findings  \
5   NEB-2020-09-12658 R                 Arcus; diameter of clear area 9 mm
6   NEB-2020-09-12659 L                 Arcus; diameter of clear area 9 mm
7   NEB-2020-09-12660 L  Clear; arcus ("mild arcus"); diameter of clear...
8   NEB-2020-09-12661 R  Clear; arcus ("mild arcus"); diameter of clear...
9   NEB-2020-09-12662 L  Clear; arcus ("mild arcus"); diameter of clear...
10  NEB-2020-09-12663 R        Clear; arcus; diameter of clear area 8.5 mm
11  NEB-2020-09-12664 R  Clear; arcus ("mild arcus"); diameter of clear...
12  NEB-2020-09-12665 L  Clear; arcus ("mild arcus"); diameter of clear...
13  NEB-2020-09-12666 L  Clear; arcus ("moderate arcus"); diameter of c...
14  NEB-2020-09-12667 R        Clear; arcus; diameter of clear area 7.5 mm
15  NEB-2020-09-12668 L                 Arcus; diameter of clear area 8 mm
16  NEB-2020-09-12669 R        Clear; arcus; diameter of clear area 7.5 mm
17  NEB-2020-09-12670 R        Clear; arcus; diameter of clear area 7.5 mm
18  NEB-2020-09-12671 L               Arcus; diameter of clear area 7.5 mm
20  NEB-2020-09-12673 L  Arcus ("mild arcus"); diameter of clear area 9 mm
21  NEB-2020-09-12674 L  Arcus ("mild arcus"); diameter of clear area 8 mm
22  NEB-2020-09-12675 R  Arcus ("mild arcus"); diameter of clear area 8 mm
23  NEB-2020-09-12676 L  Diameter of clear area 8 mm (no stromal box ti...
24  NEB-2020-09-12677 R  Diameter of clear area 8 mm (no stromal box ti...
25  NEB-2020-09-12678 L    Arcus; scar: phaco; diameter of clear area 8 mm

    Stroma_Clear_Area_Diameter_mm
5                             9.0
6                             9.0
7                             8.0
8                             8.0
9                             8.5
10                            8.5
11                            8.5
12                            8.5
13                            7.5
14                            7.5
15                            8.0
16                            7.5
17                            7.5
18                            7.5
20                            9.0
21                            8.0
22                            8.0
23                            8.0
24                            8.0
25                            8.0

In [181]:
print(df["Stroma_Clear_Area_Diameter_mm"].describe())

count    555.000000
mean       8.417748
std        0.571562
min        6.000000
25%        8.000000
50%        8.500000
75%        9.000000
max       10.000000
Name: Stroma_Clear_Area_Diameter_mm, dtype: float64

In [183]:
for col in [
    "Stroma_Is_Clear",
    "Stroma_Is_Compact",
    "Stroma_Has_Arcus",
    "Stroma_Has_Edema",
    "Stroma_Arcus_Severity",
    "Stroma_Scar_Type",
]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Stroma_Is_Clear ---
Stroma_Is_Clear
True     577
<NA>     467
False     11
Name: count, dtype: int64

--- Stroma_Is_Compact ---
Stroma_Is_Compact
<NA>     467
False    358
True     230
Name: count, dtype: int64

--- Stroma_Has_Arcus ---
Stroma_Has_Arcus
True     486
<NA>     467
False    102
Name: count, dtype: int64

--- Stroma_Has_Edema ---
Stroma_Has_Edema
False    578
<NA>     467
True      10
Name: count, dtype: int64

--- Stroma_Arcus_Severity ---
Stroma_Arcus_Severity
NaN            467
Unspecified    437
None           102
Mild            43
Moderate         6
Name: count, dtype: int64

--- Stroma_Scar_Type ---
Stroma_Scar_Type
None          555
<NA>          467
Other scar     27
Phaco scar      6
Name: count, dtype: int64

In [184]:
descemet_features = [
    "Descemet_Review_Flag",
    "Descemet_Has_Folds",
    "Descemet_Fold_Severity",
    "Descemet_Fold_Relative_Number",
]

for col in descemet_features:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Descemet_Review_Flag ---
Descemet_Review_Flag
False    544
<NA>     469
True      42
Name: count, dtype: int64

--- Descemet_Has_Folds ---
Descemet_Has_Folds
True     535
<NA>     511
False      9
Name: count, dtype: int64

--- Descemet_Fold_Severity ---
Descemet_Fold_Severity
NaN            511
Mild           387
Unspecified    118
Moderate        21
Very mild       18
Name: count, dtype: int64

--- Descemet_Fold_Relative_Number ---
Descemet_Fold_Relative_Number
NaN                 511
Unspecified         261
Mild                252
Several              28
Moderate              2
Several/Moderate      1
Name: count, dtype: int64

In [185]:
endo_features = [
    "Endo_Has_Stress_Lines",
    "Endo_Stress_Line_Location",
    "Endo_Stress_Line_Amount",
    "Endo_Has_Cell_Dropout",
    "Endo_Cell_Dropout_Severity",
    "Endo_Has_RBC",
    "Endo_RBC_Severity",
]

for col in endo_features:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Endo_Has_Stress_Lines ---
Endo_Has_Stress_Lines
True     499
<NA>     480
False     76
Name: count, dtype: int64

--- Endo_Stress_Line_Location ---
Endo_Stress_Line_Location
NaN                     480
Central                 243
Unspecified             174
Peripheral               67
None                     63
Central + Peripheral     28
Name: count, dtype: int64

--- Endo_Stress_Line_Amount ---
Endo_Stress_Line_Amount
NaN            480
Few            479
None            76
Unspecified     18
Several          2
Name: count, dtype: int64

--- Endo_Has_Cell_Dropout ---
Endo_Has_Cell_Dropout
False    482
<NA>     480
True      93
Name: count, dtype: int64

--- Endo_Cell_Dropout_Severity ---
Endo_Cell_Dropout_Severity
None        482
NaN         480
Mild         90
Moderate      3
Name: count, dtype: int64

--- Endo_Has_RBC ---
Endo_Has_RBC
False    545
<NA>     480
True      30
Name: count, dtype: int64

--- Endo_RBC_Severity ---
Endo_RBC_Severity
None           545
NaN            480
Unspecified     22
+                6
++               2
Name: count, dtype: int64

In [186]:
clinical_features = [
    "Epi_Has_Exposure",
    "Epi_Exposure_Severity",
    "Epi_Exposure_Location",
    "Epi_Has_Defect",
    "Epi_Has_Haze",
    "Epi_Haze_Severity",
    "Epi_Has_Arcus",
    "Stroma_Clear_Area_Diameter_mm",
    "Stroma_Is_Clear",
    "Stroma_Is_Compact",
    "Stroma_Has_Arcus",
    "Stroma_Has_Edema",
    "Stroma_Arcus_Severity",
    "Stroma_Scar_Type",
    "Descemet_Review_Flag",
    "Descemet_Has_Folds",
    "Descemet_Fold_Severity",
    "Descemet_Fold_Relative_Number",
    "Endo_Has_Stress_Lines",
    "Endo_Stress_Line_Location",
    "Endo_Stress_Line_Amount",
    "Endo_Has_Cell_Dropout",
    "Endo_Cell_Dropout_Severity",
    "Endo_Has_RBC",
    "Endo_RBC_Severity",
]

print("Number of clinical features:", len(clinical_features))
print("Missing feature columns:",
      [col for col in clinical_features if col not in df.columns])

print("\nSource columns still present:")
print([
    col for col in [
        "Epithelium_Findings",
        "Stroma_Findings",
        "Descemet_Findings",
        "Endothelium_Findings"
    ]
    if col in df.columns
])

print("\nDataset shape:", df.shape)

Number of clinical features: 25
Missing feature columns: []

Source columns still present:
['Epithelium_Findings', 'Stroma_Findings', 'Descemet_Findings', 'Endothelium_Findings']

Dataset shape: (1055, 113)

In [187]:
numeric_candidates = [
    "Form_ECD_cells_per_mm2",
    "Recipient_Age",
    "Donor_Graft_Size_mm",
    "Recipient_Bed_Size_mm",
    "Previous_Grafts",
]

for col in numeric_candidates:
    print(f"\n--- {col} ---")
    print(df[col].dtype)
    print(df[col].dropna().head(15).tolist())

--- Form_ECD_cells_per_mm2 ---
float64
[2132.0, 2212.0, 2538.0, 2584.0, 3115.0, 2950.0, 2993.0, 3049.0, 2833.0, 2780.0, 3049.0, 2710.0, 2625.0, 2833.0, 3012.0]

--- Recipient_Age ---
object
[48, 64, 53, 57, '2 y 3 m', '35', 80, '60 (as read)', 68, 47, 14, 69, '72 (as read)', 55, 21]

--- Donor_Graft_Size_mm ---
object
[8.25, 8, 8.5, 7.5, 8.5, 9, 7, 11, 7.5, 8, 8, '8-8.5', '8 (as read)', 8.25, 8]

--- Recipient_Bed_Size_mm ---
object
[8, 8.5, 8, 8, 8.25, 7.5, 7, 8.5, 8.25, '8 (as read)', '8 (as read)', 7.5, 9, '11.5 (as read)', 8.5]

--- Previous_Grafts ---
object
['1', '2', '1', 'Not ticked (diagnosis implies >=1)', '1', '1', 'Not ticked', '1', 'Not ticked', '>=1 (repeat PK)', 0, 1, 0, 1, 2]

In [193]:
def clean_graft_size(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).strip().lower()

    # Ignore written fractions such as "2/3 cornea"
    if re.search(r"\d+\s*/\s*\d+", text):
        return pd.NA

    # Handle ranges, including annotations such as "10-11 (as read)"
    range_match = re.search(
        r"(\d+(?:\.\d+)?)\s*-\s*(\d+(?:\.\d+)?)",
        text
    )

    if range_match:
        low = float(range_match.group(1))
        high = float(range_match.group(2))
        return (low + high) / 2

    # Handle single numeric values, including "(as read)"
    match = re.search(r"\b\d+(?:\.\d+)?\b", text)

    if match:
        return float(match.group())

    return pd.NA


df["Donor_Graft_Size_Clean_mm"] = (
    df["Donor_Graft_Size_mm"]
    .apply(clean_graft_size)
)

df["Donor_Graft_Size_Clean_mm"] = pd.to_numeric(
    df["Donor_Graft_Size_Clean_mm"],
    errors="coerce"
)

In [194]:
df.loc[
    df["Donor_Graft_Size_mm"].astype(str).str.contains(
        r"-|/|\(|as read|as written",
        case=False,
        na=False
    ),
    ["Tissue_ID", "Donor_Graft_Size_mm", "Donor_Graft_Size_Clean_mm"]
]

,Tissue_ID,Donor_Graft_Size_mm,Donor_Graft_Size_Clean_mm
27,NEB-2020-09-12680 R,8-8.5,8.25
28,NEB-2020-09-12681 L,8 (as read),8.00
37,NEB-2020-09-12690 L,11 (as read),11.00
57,NEB-2020-10-12710 L,10-11 (as read),10.50
60,NEB-2020-10-12713 R,8.5 (as read),8.50
114,NEB-2020-11-12816 R,8 (as read),8.00
233,NEB-2024-05-16063 R,14 (as read),14.00
241,NEB-2024-05-16071 R,14 (as read),14.00
284,NEB-2024-06-16115 L,11 (as read),11.00
288,NEB-2024-06-16119 R,8.5 (as read),8.50
334,NEB-2024-08-16267 R,7 (as read),7.00
343,NEB-2024-08-16276 R,9 (as read),9.00
454,NEB-2025-09-17506 R,8.75 (as read),8.75
465,NEB-2025-09-17517 R,8.00 (LK page donor diameter),8.00
469,NEB-2025-09-17521 L,11 (as read),11.00
570,NEB-2025-11-17628 R,2/3 cornea (as written),NaN

In [196]:
print(df["Donor_Graft_Size_Clean_mm"].describe())

count    232.000000
mean       8.695259
std        1.282027
min        6.000000
25%        8.000000
50%        8.250000
75%        9.000000
max       14.000000
Name: Donor_Graft_Size_Clean_mm, dtype: float64

In [198]:
print(df.loc[
    df["Donor_Graft_Size_mm"].astype(str).str.contains(
        r"2/3|10-11",
        case=False,
        na=False
    ),
    ["Tissue_ID", "Donor_Graft_Size_mm", "Donor_Graft_Size_Clean_mm"]
])

               Tissue_ID      Donor_Graft_Size_mm  Donor_Graft_Size_Clean_mm
57   NEB-2020-10-12710 L          10-11 (as read)                       10.5
570  NEB-2025-11-17628 R  2/3 cornea (as written)                        NaN

In [199]:
df.loc[
    df["Recipient_Bed_Size_mm"].astype(str).str.contains(
        r"-|\(|as read|as written",
        case=False,
        na=False
    ),
    ["Tissue_ID", "Recipient_Bed_Size_mm"]
]

               Tissue_ID       Recipient_Bed_Size_mm
28   NEB-2020-09-12681 L                 8 (as read)
31   NEB-2020-09-12684 R                 8 (as read)
37   NEB-2020-09-12690 L              11.5 (as read)
59   NEB-2020-10-12712 L               8.5 (as read)
80   NEB-2020-10-12735 R                10 (as read)
124  NEB-2020-11-12829 R                11 (as read)
233  NEB-2024-05-16063 R                12 (as read)
241  NEB-2024-05-16071 R                12 (as read)
287  NEB-2024-06-16118 L               8.5 (as read)
321  NEB-2024-08-16254 L                11 (as read)
463  NEB-2025-09-17515 R                 9 (as read)
478  NEB-2025-09-17530 R               8.7 (as read)
570  NEB-2025-11-17628 R  2/3 of cornea (as written)

In [200]:
print(df["Recipient_Bed_Size_mm"].value_counts(dropna=False).head(30))

Recipient_Bed_Size_mm
NaN                           862
8                              67
8.5                            21
8.25                           19
7.5                            12
7                              12
9                              10
7.75                            8
9.5                             6
10                              6
12                              5
11                              5
10.5                            3
8 (as read)                     2
8.5 (as read)                   2
11 (as read)                    2
8.75                            2
12 (as read)                    2
11.5 (as read)                  1
6.5                             1
10 (as read)                    1
Freehand                        1
14                              1
9 (as read)                     1
7.25                            1
8.7 (as read)                   1
2/3 of cornea (as written)      1
Name: count, dtype: int64

In [201]:
def clean_bed_size(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).strip().lower()

    # Written fraction, not a numeric diameter
    if re.search(r"\d+\s*/\s*\d+", text):
        return pd.NA

    # Numeric value, including "(as read)"
    match = re.search(r"\b\d+(?:\.\d+)?\b", text)

    if match:
        return float(match.group())

    return pd.NA


df["Recipient_Bed_Size_Clean_mm"] = (
    df["Recipient_Bed_Size_mm"]
    .apply(clean_bed_size)
)

df["Recipient_Bed_Size_Clean_mm"] = pd.to_numeric(
    df["Recipient_Bed_Size_Clean_mm"],
    errors="coerce"
)

df["Recipient_Bed_Size_Clean_mm"].describe()

count    191.000000
mean       8.503665
std        1.198491
min        6.500000
25%        8.000000
50%        8.000000
75%        8.500000
max       14.000000
Name: Recipient_Bed_Size_Clean_mm, dtype: float64

In [203]:
print(df.loc[
    df["Recipient_Bed_Size_mm"].astype(str).str.contains(
        r"freehand|2/3",
        case=False,
        na=False
    ),
    ["Tissue_ID", "Recipient_Bed_Size_mm", "Recipient_Bed_Size_Clean_mm"]
])

               Tissue_ID       Recipient_Bed_Size_mm  \
238  NEB-2024-05-16068 L                    Freehand
570  NEB-2025-11-17628 R  2/3 of cornea (as written)

     Recipient_Bed_Size_Clean_mm
238                          NaN
570                          NaN

In [204]:
df["Recipient_Bed_Size_Clean_mm"].describe()

count    191.000000
mean       8.503665
std        1.198491
min        6.500000
25%        8.000000
50%        8.000000
75%        8.500000
max       14.000000
Name: Recipient_Bed_Size_Clean_mm, dtype: float64

In [206]:
print(df.loc[
    df["Recipient_Bed_Size_mm"].astype(str).str.contains(
        r"\(as read\)",
        case=False,
        na=False
    ),
    ["Tissue_ID", "Recipient_Bed_Size_mm", "Recipient_Bed_Size_Clean_mm"]
])

               Tissue_ID Recipient_Bed_Size_mm  Recipient_Bed_Size_Clean_mm
28   NEB-2020-09-12681 L           8 (as read)                          8.0
31   NEB-2020-09-12684 R           8 (as read)                          8.0
37   NEB-2020-09-12690 L        11.5 (as read)                         11.5
59   NEB-2020-10-12712 L         8.5 (as read)                          8.5
80   NEB-2020-10-12735 R          10 (as read)                         10.0
124  NEB-2020-11-12829 R          11 (as read)                         11.0
233  NEB-2024-05-16063 R          12 (as read)                         12.0
241  NEB-2024-05-16071 R          12 (as read)                         12.0
287  NEB-2024-06-16118 L         8.5 (as read)                          8.5
321  NEB-2024-08-16254 L          11 (as read)                         11.0
463  NEB-2025-09-17515 R           9 (as read)                          9.0
478  NEB-2025-09-17530 R         8.7 (as read)                          8.7

In [207]:
print(df["Recipient_Bed_Size_Clean_mm"].describe())

count    191.000000
mean       8.503665
std        1.198491
min        6.500000
25%        8.000000
50%        8.000000
75%        8.500000
max       14.000000
Name: Recipient_Bed_Size_Clean_mm, dtype: float64

In [208]:
print(df["Previous_Grafts"].value_counts(dropna=False))

Previous_Grafts
NaN                                                982
1                                                   30
1                                                   10
Not ticked                                           8
Not recorded                                         5
2                                                    4
Not ticked (diagnosis implies >=1)                   2
0                                                    2
2                                                    2
None (as read)                                       2
>=1 (repeat PK)                                      1
None (ticked - but diagnosis is rejected graft)      1
None marked and "1" written (as read)                1
3                                                    1
None marked and "2" written (as read)                1
1 (per letter; not ticked on request form)           1
2 (as read)                                          1
None (debulking + conjunctival flap graft done)      1
Name: count, dtype: int64

In [210]:
previous_graft_special = [
    "Not ticked",
    "Not recorded",
    "Not ticked (diagnosis implies >=1)",
    "None (as read)",
    ">=1 (repeat PK)",
    "None (ticked - but diagnosis is rejected graft)",
    'None marked and "1" written (as read)',
    'None marked and "2" written (as read)',
    "1 (per letter; not ticked on request form)",
    "2 (as read)",
    "None (debulking + conjunctival flap graft done)",
]

print(df.loc[
    df["Previous_Grafts"].isin(previous_graft_special),
    ["Tissue_ID", "Previous_Grafts", "Tissue_Grade_Clean", "Disease_Label"]
])

               Tissue_ID                                  Previous_Grafts  \
51   NEB-2020-09-12704 L               Not ticked (diagnosis implies >=1)
59   NEB-2020-10-12712 L                                       Not ticked
82   NEB-2020-10-12737 L                                       Not ticked
179  NEB-2022-10-14306 R                                  >=1 (repeat PK)
244  NEB-2024-05-16074 R               Not ticked (diagnosis implies >=1)
293  NEB-2024-06-16124 R  None (ticked - but diagnosis is rejected graft)
297  NEB-2024-06-16128 L            None marked and "1" written (as read)
303  NEB-2024-06-16134 R            None marked and "2" written (as read)
378  NEB-2024-12-16628 L                                       Not ticked
390  NEB-2024-12-16640 R                                       Not ticked
393  NEB-2024-12-16644 L                                     Not recorded
420  NEB-2025-09-17472 L       1 (per letter; not ticked on request form)
445  NEB-2025-09-17497 R                                       Not ticked
450  NEB-2025-09-17502 L                                   None (as read)
465  NEB-2025-09-17517 R                                   None (as read)
502  NEB-2025-10-17555 R                                     Not recorded
518  NEB-2025-10-17572 L                                     Not recorded
543  NEB-2025-10-17597 R                                     Not recorded
546  NEB-2025-10-17600 R                                     Not recorded
550  NEB-2025-10-17605 L                                       Not ticked
557  NEB-2025-10-17614 R                                       Not ticked
570  NEB-2025-11-17628 R                                       Not ticked
584  NEB-2025-11-17644 L                                      2 (as read)
585  NEB-2025-11-17645 R  None (debulking + conjunctival flap graft done)

    Tissue_Grade_Clean                                      Disease_Label
51                   A                                             Normal
59                   B  FECD; Polymorphism and pleomorphism; Low cell ...
82                   A                                              Folds
179                 A+                                             Normal
244                 A+                                              Folds
293                  A                                             Normal
297                 A+                                             Normal
303                 A+                                              Folds
378                 A+                                             Normal
390                  A                                              Folds
393                  A                                            Guttata
420                  A                                             Normal
445                  A                                             Normal
450                 A+                                             Normal
465                 A+                                            Guttata
502                  A                                     Guttata; Folds
518                  A                                             Normal
543                  A                                            Guttata
546                 A+                                            Guttata
550                 A+                                             Normal
557                  A                                     Guttata; Folds
570                  B      Folds; Guttata; Polymorphism and pleomorphism
584                  A                          Low cell density; Guttata
585                 A+                                            Guttata

In [211]:
previous_grafts_mapping = {
    "Not ticked": "Unknown",
    "Not recorded": "Unknown",
    "Not ticked (diagnosis implies >=1)": ">=1",
    ">=1 (repeat PK)": ">=1",
    "None (as read)": "0",
    "None (ticked - but diagnosis is rejected graft)": "0",
    'None marked and "1" written (as read)': "1",
    'None marked and "2" written (as read)': "2",
    "1 (per letter; not ticked on request form)": "1",
    "2 (as read)": "2",
    "None (debulking + conjunctival flap graft done)": "0",
}

In [213]:
print(df["Previous_Grafts"].map(type).value_counts())

Previous_Grafts
<class 'float'>    982
<class 'str'>       59
<class 'int'>       14
Name: count, dtype: int64

In [215]:
def clean_previous_grafts(value):
    if pd.isna(value):
        return pd.NA

    text = str(value).strip().lower()

    # Explicit / documented values
    if text in {"0", "none (as read)",
                "none (ticked - but diagnosis is rejected graft)",
                "none (debulking + conjunctival flap graft done)"}:
        return "0"

    if text in {"1", 'none marked and "1" written (as read)',
                "1 (per letter; not ticked on request form)"}:
        return "1"

    if text in {"2", 'none marked and "2" written (as read)',
                "2 (as read)"}:
        return "2"

    if text == "3":
        return "3"

    if text in {
        "not ticked",
        "not recorded",
    }:
        return "Unknown"

    if text in {
        "not ticked (diagnosis implies >=1)",
        ">=1 (repeat pk)",
    }:
        return ">=1"

    return "Unknown"


df["Previous_Grafts_Clean"] = (
    df["Previous_Grafts"]
    .apply(clean_previous_grafts)
)

print(df["Previous_Grafts_Clean"].value_counts(dropna=False))

Previous_Grafts_Clean
NaN        982
1           42
Unknown     13
2            8
0            6
>=1          3
3            1
Name: count, dtype: int64

In [216]:
print(
    "Original non-missing:",
    df["Previous_Grafts"].notna().sum()
)

print(
    "Clean non-missing:",
    df["Previous_Grafts_Clean"].notna().sum()
)

print(
    "Unexpected clean values:",
    sorted(
        set(df["Previous_Grafts_Clean"].dropna().unique())
        - {"0", "1", "2", "3", ">=1", "Unknown"}
    )
)

Original non-missing: 73
Clean non-missing: 73
Unexpected clean values: []

In [217]:
candidate_columns = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2",
    "Form_ECD_cells_per_mm2",
    "Donor_Age",
    "Recipient_Age_Clean",
    "Donor_Graft_Size_Clean_mm",
    "Recipient_Bed_Size_Clean_mm",
    "Previous_Grafts_Clean",
    "Clinical_Findings_Available",
]

for col in candidate_columns:
    print(
        f"{col:35} | "
        f"dtype={df[col].dtype} | "
        f"non-null={df[col].notna().sum()}"
    )

ECD_CD_cells_per_mm2                | dtype=float64 | non-null=952
CV                                  | dtype=float64 | non-null=952
HEX_percent                         | dtype=float64 | non-null=952
SD                                  | dtype=float64 | non-null=951
Total_Cell_Count                    | dtype=float64 | non-null=952
Total_Area_um2                      | dtype=float64 | non-null=952
Form_ECD_cells_per_mm2              | dtype=float64 | non-null=575
Donor_Age                           | dtype=float64 | non-null=1050
Recipient_Age_Clean                 | dtype=float64 | non-null=295
Donor_Graft_Size_Clean_mm           | dtype=float64 | non-null=232
Recipient_Bed_Size_Clean_mm         | dtype=float64 | non-null=191
Previous_Grafts_Clean               | dtype=str | non-null=73
Clinical_Findings_Available         | dtype=int64 | non-null=1055

In [220]:
print(df["Donor_Age"].describe())

count    1050.000000
mean       59.672381
std        10.901732
min        15.000000
25%        54.000000
50%        62.000000
75%        68.000000
max        78.000000
Name: Donor_Age, dtype: float64

In [221]:
print(df.loc[
    (df["Donor_Age"] < 0) | (df["Donor_Age"] > 120),
    ["Tissue_ID", "Donor_Age"]
])

Empty DataFrame
Columns: [Tissue_ID, Donor_Age]
Index: []

In [222]:
grading_numeric_candidates = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2",
    "Form_ECD_cells_per_mm2",
    "Donor_Age",
]

missing_summary = pd.DataFrame({
    "Missing_Count": df[grading_numeric_candidates].isna().sum(),
    "Missing_Percent": (
        df[grading_numeric_candidates].isna().mean() * 100
    ).round(2)
})

missing_summary.sort_values(
    "Missing_Percent",
    ascending=False
)

                        Missing_Count  Missing_Percent
Form_ECD_cells_per_mm2            480            45.50
SD                                104             9.86
CV                                103             9.76
ECD_CD_cells_per_mm2              103             9.76
HEX_percent                       103             9.76
Total_Cell_Count                  103             9.76
Total_Area_um2                    103             9.76
Donor_Age                           5             0.47

In [225]:
konan_cols = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2",
]

print(df[konan_cols].isna().value_counts())

ECD_CD_cells_per_mm2  CV     HEX_percent  SD     Total_Cell_Count  Total_Area_um2
False                 False  False        False  False             False             951
True                  True   True         True   True              True              103
False                 False  False        True   False             False               1
Name: count, dtype: int64

In [226]:
print(df.loc[
    df[konan_cols].isna().all(axis=1),
    [
        "Tissue_ID",
        "Tissue_Grade_Clean",
        "Konan_Report_File",
        "SP_Image_File",
        "Cell_Image_File"
    ]
].head(20))

                       Tissue_ID Tissue_Grade_Clean Konan_Report_File  \
0   12346 R (year/month unknown)                NaN               NaN
30           NEB-2020-09-12683 L                 A+               NaN
49           NEB-2020-09-12702 R                 A+               NaN
50           NEB-2020-09-12703 L                 A+               NaN
51           NEB-2020-09-12704 L                  A               NaN
52           NEB-2020-09-12705 R                  A               NaN
53           NEB-2020-10-12706 R                  A               NaN
54           NEB-2020-10-12707 L                  A               NaN
55           NEB-2020-10-12708 L                  B               NaN
56           NEB-2020-10-12709 R                  B               NaN
57           NEB-2020-10-12710 L                 A+               NaN
58           NEB-2020-10-12711 R                 A+               NaN
59           NEB-2020-10-12712 L                  B               NaN
60           NEB-2020-10-12713 R                  B               NaN
61           NEB-2020-10-12715 R                 A+               NaN
62           NEB-2020-10-12716 R                 A+               NaN
63           NEB-2020-10-12717 L                 A+               NaN
64           NEB-2020-10-12718 L                 A+               NaN
65           NEB-2020-10-12719 R                 A+               NaN
66           NEB-2020-10-12720 L                 A+               NaN

   SP_Image_File Cell_Image_File
0            NaN             NaN
30           NaN             NaN
49           NaN             NaN
50           NaN             NaN
51           NaN             NaN
52           NaN             NaN
53           NaN             NaN
54           NaN             NaN
55           NaN             NaN
56           NaN             NaN
57           NaN             NaN
58           NaN             NaN
59           NaN             NaN
60           NaN             NaN
61           NaN             NaN
62           NaN             NaN
63           NaN             NaN
64           NaN             NaN
65           NaN             NaN
66           NaN             NaN

In [227]:
konan_missing = df[konan_cols].isna().all(axis=1)

df.loc[
    konan_missing,
    [
        "Tissue_ID",
        "Tissue_Grade_Clean",
        "Tissue_Grade_Source",
        "Dataset_Part",
        "Konan_Report_File",
        "SP_Image_File",
        "Cell_Image_File"
    ]
].isna().sum()

Tissue_ID               0
Tissue_Grade_Clean      7
Tissue_Grade_Source     6
Dataset_Part            0
Konan_Report_File      93
SP_Image_File          88
Cell_Image_File        89
dtype: int64

In [229]:
print(df.loc[
    konan_missing,
    "Tissue_Grade_Clean"
].value_counts(dropna=False))

Tissue_Grade_Clean
A+     40
A      38
B      18
NaN     7
Name: count, dtype: int64

In [230]:
konan_missing = df[konan_cols].isna().all(axis=1)

df.loc[konan_missing, "Tissue_ID"].astype(str).str.extract(
    r"NEB-(\d{4})-"
)[0].value_counts().sort_index()

0
2020    56
2021     1
2022     5
2023     5
2024    19
2025    15
Name: count, dtype: int64

In [232]:
konan_available = ~df[konan_cols].isna().all(axis=1)

print(pd.DataFrame({
    "Konan_Available": df.loc[konan_available, "Tissue_ID"]
        .astype(str).str.extract(r"NEB-(\d{4})-")[0].value_counts(),
    "Konan_Missing": df.loc[konan_missing, "Tissue_ID"]
        .astype(str).str.extract(r"NEB-(\d{4})-")[0].value_counts()
}).fillna(0).astype(int))

      Konan_Available  Konan_Missing
0
2020               88             56
2021               12              1
2022               58              5
2023              459              5
2024              159             19
2025              176             15

In [234]:
form_ecd_missing = df["Form_ECD_cells_per_mm2"].isna()

print(df.loc[
    form_ecd_missing,
    [
        "Tissue_ID",
        "Tissue_Grade_Clean",
        "Tissue_Grade_Source",
        "Dataset_Part",
        "ECD_CD_cells_per_mm2",
        "Form_ECD_cells_per_mm2"
    ]
].head(20))

                        Tissue_ID Tissue_Grade_Clean Tissue_Grade_Source  \
0    12346 R (year/month unknown)                NaN                 NaN
61            NEB-2020-10-12715 R                 A+       Eye-bank form
64            NEB-2020-10-12718 L                 A+       Eye-bank form
87            NEB-2020-10-12742 R                  A       Eye-bank form
97            NEB-2020-10-12761 R                NaN                 NaN
174  14302 L (year/month unknown)                NaN                 NaN
285           NEB-2024-06-16116 L                NaN                 NaN
286           NEB-2024-06-16117 R                NaN                 NaN
306           NEB-2024-06-16137 L                NaN                 NaN
319           NEB-2024-08-16252 L                 A+       Eye-bank form
325           NEB-2024-08-16258 L                 A+       Eye-bank form
367           NEB-2024-08-16300 R                  B       Eye-bank form
368           NEB-2024-08-16301 L                  B       Eye-bank form
373           NEB-2024-12-16605 L                NaN                 NaN
575           NEB-2025-11-17635 R                  B       Eye-bank form
576           NEB-2025-11-17636 L                  B       Eye-bank form
591           NEB-2023-01-14657 R                NaN       Eye-bank form
592           NEB-2023-01-14659 R                  A       Eye-bank form
593           NEB-2023-01-14662 R                 A+       Eye-bank form
594           NEB-2023-01-14664 R                 A+       Eye-bank form

                    Dataset_Part  ECD_CD_cells_per_mm2  Form_ECD_cells_per_mm2
0    Graded set (eye-bank forms)                   NaN                     NaN
61   Graded set (eye-bank forms)                   NaN                     NaN
64   Graded set (eye-bank forms)                   NaN                     NaN
87   Graded set (eye-bank forms)                   NaN                     NaN
97   Graded set (eye-bank forms)                   NaN                     NaN
174  Graded set (eye-bank forms)                   NaN                     NaN
285  Graded set (eye-bank forms)                   NaN                     NaN
286  Graded set (eye-bank forms)                   NaN                     NaN
306  Graded set (eye-bank forms)                   NaN                     NaN
319  Graded set (eye-bank forms)                2421.0                     NaN
325  Graded set (eye-bank forms)                3096.0                     NaN
367  Graded set (eye-bank forms)                   NaN                     NaN
368  Graded set (eye-bank forms)                   NaN                     NaN
373  Graded set (eye-bank forms)                2304.0                     NaN
575  Graded set (eye-bank forms)                   NaN                     NaN
576  Graded set (eye-bank forms)                   NaN                     NaN
591  Graded set (eye-bank forms)                   NaN                     NaN
592  Graded set (eye-bank forms)                2387.0                     NaN
593  Graded set (eye-bank forms)                2688.0                     NaN
594  Graded set (eye-bank forms)                2667.0                     NaN

In [236]:
print(df.loc[
    form_ecd_missing,
    "Tissue_Grade_Clean"
].value_counts(dropna=False))

Tissue_Grade_Clean
A+     260
A      120
B       92
NaN      8
Name: count, dtype: int64

In [237]:
ecd_source_overlap = pd.DataFrame({
    "Konan_ECD_Available": df["ECD_CD_cells_per_mm2"].notna(),
    "Form_ECD_Available": df["Form_ECD_cells_per_mm2"].notna()
})

print(ecd_source_overlap.value_counts())

Konan_ECD_Available  Form_ECD_Available
True                 True                  490
                     False                 462
False                True                   85
                     False                  18
Name: count, dtype: int64

In [238]:
df.loc[
    df["SD"].isna() &
    df["ECD_CD_cells_per_mm2"].notna(),
    [
        "Tissue_ID",
        "Tissue_Grade_Clean",
        "ECD_CD_cells_per_mm2",
        "CV",
        "HEX_percent",
        "SD",
        "Total_Cell_Count",
        "Total_Area_um2"
    ]
]

,Tissue_ID,Tissue_Grade_Clean,ECD_CD_cells_per_mm2,CV,HEX_percent,SD,Total_Cell_Count,Total_Area_um2
273,NEB-2024-05-16103 R,B,2203.0,50.0,42.0,NaN,99.0,44938.0

In [239]:
df.loc[
    df["ECD_CD_cells_per_mm2"].notna() &
    df["SD"].isna(),
    "SD"
] = 229

In [240]:
df["SD"].isna().sum()

np.int64(103)

In [241]:
grading_numeric_candidates = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2",
    "Donor_Age",
]

In [243]:
grading_numeric_candidates = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2",
    "Donor_Age",
]

print(df[grading_numeric_candidates].describe().T)

                       count          mean          std     min      25%  \
ECD_CD_cells_per_mm2   952.0   2592.400210   438.998119   676.0   2336.0
CV                     952.0     38.130252     4.993776    24.0     35.0
HEX_percent            952.0     54.032563     6.437436    27.0     50.0
SD                     952.0    153.080882    47.739818    86.0    127.0
Total_Cell_Count       952.0    107.018908    16.351349    10.0    104.0
Total_Area_um2         952.0  42265.138655  9122.697304  5071.0  37512.5
Donor_Age             1050.0     59.672381    10.901732    15.0     54.0

                          50%       75%       max
ECD_CD_cells_per_mm2   2591.0   2857.00    4484.0
CV                       38.0     41.00      74.0
HEX_percent              54.0     58.00      76.0
SD                      144.0    164.25     753.0
Total_Cell_Count        108.0    113.00     204.0
Total_Area_um2        41464.5  46336.50  100692.0
Donor_Age                62.0     68.00      78.0

In [244]:
outlier_check_cols = [
    "ECD_CD_cells_per_mm2",
    "CV",
    "HEX_percent",
    "SD",
    "Total_Cell_Count",
    "Total_Area_um2",
]

for col in outlier_check_cols:
    print(f"\n--- {col} ---")
    print(
        df.loc[
            df[col].notna(),
            ["Tissue_ID", "Tissue_Grade_Clean", col]
        ]
        .sort_values(col)
        .head(5)
    )
    print(
        df.loc[
            df[col].notna(),
            ["Tissue_ID", "Tissue_Grade_Clean", col]
        ]
        .sort_values(col, ascending=False)
        .head(5)
    )

--- ECD_CD_cells_per_mm2 ---
               Tissue_ID Tissue_Grade_Clean  ECD_CD_cells_per_mm2
105  NEB-2020-11-12807 L                  B                 676.0
562  NEB-2025-11-17620 R                  B                 788.0
161  NEB-2022-04-13824 R                  B                 905.0
823  NEB-2023-06-15129 R                  B                 951.0
881  NEB-2023-07-15250 R                  B                1008.0
               Tissue_ID Tissue_Grade_Clean  ECD_CD_cells_per_mm2
298  NEB-2024-06-16129 R                  A                4484.0
716  NEB-2023-03-14912 R                 A+                4032.0
129  NEB-2020-11-12835 R                  A                3831.0
205  NEB-2022-10-14333 R                  A                3774.0
971  NEB-2023-10-15440 R                  A                3759.0

--- CV ---
               Tissue_ID Tissue_Grade_Clean    CV
967  NEB-2023-10-15432 R                 A+  24.0
644  NEB-2023-02-14764 R                  B  24.0
529  NEB-2025-10-17583 R                 A+  25.0
795  NEB-2023-05-15069 R                  B  25.0
411  NEB-2025-09-17463 L                  A  26.0
               Tissue_ID Tissue_Grade_Clean    CV
449  NEB-2025-09-17501 R                  A  74.0
858  NEB-2023-06-15203 R                  B  62.0
542  NEB-2025-10-17596 L                  B  61.0
783  NEB-2023-05-15044 R                 A+  60.0
733  NEB-2023-04-14944 R                  A  59.0

--- HEX_percent ---
               Tissue_ID Tissue_Grade_Clean  HEX_percent
105  NEB-2020-11-12807 L                  B         27.0
120  NEB-2020-11-12824 L                  B         33.0
145  NEB-2021-02-12970 R                  B         35.0
37   NEB-2020-09-12690 L                  A         38.0
913  NEB-2023-08-15318 R                  A         38.0
                Tissue_ID Tissue_Grade_Clean  HEX_percent
744   NEB-2023-04-14965 R                 A+         76.0
960   NEB-2023-09-15415 R                  B         73.0
25    NEB-2020-09-12678 L                  B         72.0
524   NEB-2025-10-17578 L                  B         72.0
1048  NEB-2023-12-15599 R                  B         72.0

--- SD ---
               Tissue_ID Tissue_Grade_Clean    SD
98   NEB-2020-10-12763 L                NaN  86.0
635  NEB-2023-02-14744 R                 A+  86.0
118  NEB-2020-11-12821 L                 A+  87.0
43   NEB-2020-09-12696 R                 A+  88.0
100  NEB-2020-11-12802 R                 A+  91.0
               Tissue_ID Tissue_Grade_Clean     SD
105  NEB-2020-11-12807 L                  B  753.0
858  NEB-2023-06-15203 R                  B  569.0
161  NEB-2022-04-13824 R                  B  546.0
562  NEB-2025-11-17620 R                  B  466.0
761  NEB-2023-04-15000 R                  B  425.0

--- Total_Cell_Count ---
               Tissue_ID Tissue_Grade_Clean  Total_Cell_Count
644  NEB-2023-02-14764 R                  B              10.0
120  NEB-2020-11-12824 L                  B              12.0
797  NEB-2023-05-15073 R                  B              16.0
105  NEB-2020-11-12807 L                  B              18.0
795  NEB-2023-05-15069 R                  B              18.0
                Tissue_ID Tissue_Grade_Clean  Total_Cell_Count
919   NEB-2023-08-15329 R                  B             204.0
878   NEB-2023-07-15244 R                 A+             169.0
1054  NEB-2023-12-15611 R                 A+             167.0
873   NEB-2023-07-15234 R                 A+             167.0
701   NEB-2023-03-14878 R                 A+             163.0

--- Total_Area_um2 ---
               Tissue_ID Tissue_Grade_Clean  Total_Area_um2
644  NEB-2023-02-14764 R                  B          5071.0
120  NEB-2020-11-12824 L                  B          5418.0
797  NEB-2023-05-15073 R                  B          7961.0
795  NEB-2023-05-15069 R                  B          8313.0
830  NEB-2023-06-15144 R                  A          9177.0
               Tissue_ID Tissue_Grade_Clean  Total_Area_um2
919  NEB-2023-08-15329 R                  B        100692.0
881  NEB-2023-07-15250 R                  B         89259.0
180  NEB-2022-10-14307 L                  B         84624.0
162  NEB-2022-04-13826 R                  B         84078.0
808  NEB-2023-05-15098 R                  B         77267.0

In [245]:
print(df.loc[
    df["Total_Cell_Count"] <= 20,
    [
        "Tissue_ID",
        "Tissue_Grade_Clean",
        "ECD_CD_cells_per_mm2",
        "CV",
        "HEX_percent",
        "SD",
        "Total_Cell_Count",
        "Total_Area_um2"
    ]
].sort_values("Total_Cell_Count"))

               Tissue_ID Tissue_Grade_Clean  ECD_CD_cells_per_mm2    CV  \
644  NEB-2023-02-14764 R                  B                1972.0  24.0
120  NEB-2020-11-12824 L                  B                2212.0  31.0
797  NEB-2023-05-15073 R                  B                2008.0  29.0
105  NEB-2020-11-12807 L                  B                 676.0  51.0
795  NEB-2023-05-15069 R                  B                2165.0  25.0
683  NEB-2023-03-14837 R                  B                1370.0  30.0

     HEX_percent     SD  Total_Cell_Count  Total_Area_um2
644         60.0  121.0              10.0          5071.0
120         33.0  138.0              12.0          5418.0
797         56.0  145.0              16.0          7961.0
105         27.0  753.0              18.0         26625.0
795         38.0  117.0              18.0          8313.0
683         68.0  218.0              19.0         13871.0

In [246]:
df.shape

(1055, 116)

In [247]:
df.columns.tolist()

['Tissue_ID',
 'Eye',
 'Image_ID',
 'Disease_Label',
 'Disease_Severity',
 'ECD_CD_cells_per_mm2',
 'CV',
 'HEX_percent',
 'SD',
 'Total_Cell_Count',
 'Total_Area_um2',
 'Epithelium_Findings',
 'Epithelium_Severity',
 'Stroma_Findings',
 'Stroma_Severity',
 'Descemet_Findings',
 'Descemet_Severity',
 'Endothelium_Findings',
 'Endothelium_Severity',
 'Additional_Findings',
 'Tissue_Grade',
 'Overall_Donor_Quality',
 'Transplant_Suitability',
 'Suitability_Reason',
 'Primary_COD',
 'Donor_Age',
 'Tissue_Serial',
 'Linkage_Status',
 'Source_PDF',
 'PDF_Pages',
 'Konan_Report_File',
 'SP_Image_File',
 'Cell_Image_File',
 'Konan_Raw_CorneaID',
 'Konan_Exam_Date',
 'Konan_Mean_Cell_Area_um2',
 'Konan_Comments',
 'Donor_Sex',
 'Admitting_Diagnosis',
 'Death_Date_Time',
 'Preservation_Date_Time',
 'Death_to_Preservation_Time',
 'Storage_Medium',
 'Serology_HBsAg',
 'Serology_HCV',
 'Serology_HIV',
 'Serology_VDRL',
 'Lens_Status',
 'Form_ECD_cells_per_mm2',
 'Intended_Use',
 'Tissue_Outcome',
 'Recipient_Age',
 'Recipient_Eye',
 'Recipient_Indication',
 'Request_Indication',
 'Previous_Grafts',
 'Primary_Procedure',
 'Secondary_Procedures',
 'Surgery_Date',
 'Donor_Graft_Size_mm',
 'Recipient_Bed_Size_mm',
 'Suture_Technique',
 'Intraop_Complications',
 'Death_to_Surgery_Days',
 'Request_Reg_No',
 'Request_Issue_No',
 'Request_Date',
 'Proposed_Op_Date',
 'Request_Urgency',
 'Request_Indication_Type',
 'Recipient_Sex',
 'VA_Operative_Eye',
 'VA_Fellow_Eye',
 'Requested_Grade',
 'Planned_Procedure',
 'Requesting_Surgeon',
 'Requesting_Hospital',
 'Request_to_Surgery_Days',
 'Grade_Request_Met',
 'Dataset_Part',
 'Tissue_Grade_Source',
 'Disease_Label_Source',
 'Needs_Review',
 'Review_Notes',
 'Tissue_Grade_Clean',
 'Recipient_Age_Clean',
 'Clinical_Findings_Available',
 'Stroma_Clear_Area_Diameter_mm',
 'Stroma_Is_Clear',
 'Stroma_Is_Compact',
 'Stroma_Has_Arcus',
 'Stroma_Has_Edema',
 'Stroma_Has_Scar',
 'Stroma_Arcus_Severity',
 'Stroma_Scar_Type',
 'Descemet_Review_Flag',
 'Descemet_Has_Folds',
 'Descemet_Fold_Severity',
 'Descemet_Fold_Relative_Number',
 'Endo_Has_Stress_Lines',
 'Endo_Stress_Line_Location',
 'Endo_Stress_Line_Amount',
 'Endo_Has_Cell_Dropout',
 'Endo_Has_RBC',
 'Endo_RBC_Severity',
 'Endo_Cell_Dropout_Severity',
 'Epi_Has_Exposure',
 'Epi_Exposure_Severity',
 'Epi_Has_Defect',
 'Epi_Has_Haze',
 'Epi_Haze_Severity',
 'Epi_Exposure_Location',
 'Epi_Has_Arcus',
 'Donor_Graft_Size_Clean_mm',
 'Recipient_Bed_Size_Clean_mm',
 'Previous_Grafts_Clean']

In [259]:
feature_role_audit = {
    "Target": [
        "Tissue_Grade_Clean",
    ],

    "Primary_Clinical_Numeric": [
        "ECD_CD_cells_per_mm2",
        "CV",
        "HEX_percent",
        "SD",
        "Total_Cell_Count",
        "Total_Area_um2",
        "Donor_Age",
    ],

    "Structured_Clinical_Findings": [
        "Clinical_Findings_Available",
        "Stroma_Clear_Area_Diameter_mm",
        "Stroma_Is_Clear",
        "Stroma_Is_Compact",
        "Stroma_Has_Arcus",
        "Stroma_Has_Edema",
        "Stroma_Has_Scar",
        "Stroma_Arcus_Severity",
        "Stroma_Scar_Type",
        "Descemet_Review_Flag",
        "Descemet_Has_Folds",
        "Descemet_Fold_Severity",
        "Descemet_Fold_Relative_Number",
        "Endo_Has_Stress_Lines",
        "Endo_Stress_Line_Location",
        "Endo_Stress_Line_Amount",
        "Endo_Has_Cell_Dropout",
        "Endo_Cell_Dropout_Severity",
        "Endo_Has_RBC",
        "Endo_RBC_Severity",
        "Epi_Has_Exposure",
        "Epi_Exposure_Severity",
        "Epi_Exposure_Location",
        "Epi_Has_Defect",
        "Epi_Has_Haze",
        "Epi_Haze_Severity",
        "Epi_Has_Arcus",
    ],

    "Secondary_or_Contextual": [
        "Form_ECD_cells_per_mm2",
        "Recipient_Age_Clean",
        "Donor_Graft_Size_Clean_mm",
        "Recipient_Bed_Size_Clean_mm",
        "Previous_Grafts_Clean",
],

    "Identifiers_and_Metadata": [
        "Tissue_ID",
        "Eye",
        "Image_ID",
        "Tissue_Serial",
        "Dataset_Part",
        "Tissue_Grade_Source",
        "Disease_Label_Source",
        "Source_PDF",
        "PDF_Pages",
        "Konan_Report_File",
        "SP_Image_File",
        "Cell_Image_File",
    ],

    "Leakage_or_Downstream": [
        "Overall_Donor_Quality",
        "Transplant_Suitability",
        "Suitability_Reason",
        "Tissue_Outcome",
        "Recipient_Age",
        "Recipient_Eye",
        "Recipient_Indication",
        "Request_Indication",
        "Primary_Procedure",
        "Secondary_Procedures",
        "Surgery_Date",
        "Requested_Grade",
        "Planned_Procedure",
        "Grade_Request_Met",
        "Review_Notes",
        "Additional_Findings",
    ],

    "Raw_Source_Columns": [
        "Tissue_Grade",
        "Disease_Label",
        "Epithelium_Findings",
        "Stroma_Findings",
        "Descemet_Findings",
        "Endothelium_Findings",
        "Recipient_Age",
        "Donor_Graft_Size_mm",
        "Recipient_Bed_Size_mm",
        "Previous_Grafts",
],
}

In [260]:
feature_role_audit["Donor_and_Context"] = [
    "Donor_Sex",
    "Admitting_Diagnosis",
    "Primary_COD",
    "Lens_Status",
    "Storage_Medium",
    "Serology_HBsAg",
    "Serology_HCV",
    "Serology_HIV",
    "Serology_VDRL",
]

feature_role_audit["Clinical_Source_Metadata"] = [
    "Disease_Severity",
    "Epithelium_Severity",
    "Stroma_Severity",
    "Descemet_Severity",
    "Endothelium_Severity",
    "Needs_Review",
    "Linkage_Status",
]

feature_role_audit["Konan_Source_Metadata"] = [
    "Konan_Raw_CorneaID",
    "Konan_Exam_Date",
    "Konan_Mean_Cell_Area_um2",
    "Konan_Comments",
]

feature_role_audit["Request_and_Surgery_Metadata"] = [
    "Intended_Use",
    "Suture_Technique",
    "Intraop_Complications",
    "Death_to_Surgery_Days",
    "Request_Reg_No",
    "Request_Issue_No",
    "Request_Date",
    "Proposed_Op_Date",
    "Request_Urgency",
    "Request_Indication_Type",
    "Request_to_Surgery_Days",
    "Requesting_Surgeon",
    "Requesting_Hospital",
    "Recipient_Sex",
    "VA_Operative_Eye",
    "VA_Fellow_Eye",
]

feature_role_audit["Administrative_and_Temporal_Metadata"] = [
    "Death_Date_Time",
    "Death_to_Preservation_Time",
    "Preservation_Date_Time",
]

In [261]:
audit_columns = [
    col
    for columns in feature_role_audit.values()
    for col in columns
]

missing_from_audit = sorted(
    set(df.columns) - set(audit_columns)
)

missing_from_audit

[]

In [264]:
[col for category, columns in feature_role_audit.items()
 for col in columns
 if col == "Recipient_Age"]

['Recipient_Age', 'Recipient_Age']

In [266]:
[
    category
    for category, columns in feature_role_audit.items()
    if "Recipient_Age" in columns
]

['Leakage_or_Downstream', 'Raw_Source_Columns']

In [267]:
from collections import Counter

column_counts = Counter(audit_columns)

duplicates_in_audit = {
    col: count
    for col, count in column_counts.items()
    if count > 1
}

duplicates_in_audit

{'Recipient_Age': 2}

In [268]:
feature_role_audit["Raw_Source_Columns"].remove("Recipient_Age")

In [269]:
duplicates_in_audit = {
    col: count
    for col, count in Counter(
        col
        for columns in feature_role_audit.values()
        for col in columns
    ).items()
    if count > 1
}

duplicates_in_audit

{}

In [270]:
missing_from_audit = sorted(
    set(df.columns) -
    {
        col
        for columns in feature_role_audit.values()
        for col in columns
    }
)

missing_from_audit

[]